import re

new_questions = [
  # -------------------------------------------------------------
  # SPORTS (25 Questions)
  # -------------------------------------------------------------
  {
    "id": "quiz_sport_1",
    "category": "Sports",
    "difficulty": "Beginner",
    "question": "How many players are on the field for one team in a standard soccer (football) match?",
    "urduQuestion": "فٹ بال کے ایک معیاری میچ میں ایک ٹیم کے کتنے کھلاڑی میدان میں ہوتے ہیں؟",
    "options": ["9", "10", "11", "12"],
    "correctAnswer": 2,
    "explanation": "Each soccer team has 11 players on the field, including the goalkeeper.",
    "urduExplanation": "فٹ بال کی ہر ٹیم میں گول کیپر سمیت 11 کھلاڑی میدان میں ہوتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_sport_2",
    "category": "Sports",
    "difficulty": "Beginner",
    "question": "What is the maximum number of strikes a batter gets before striking out in baseball?",
    "urduQuestion": "بیس بال میں بیٹر کو آؤٹ ہونے سے پہلے زیادہ سے زیادہ کتنے اسٹرائیک ملتے ہیں؟",
    "options": ["2", "3", "4", "5"],
    "correctAnswer": 1,
    "explanation": "Three strikes result in a strikeout in baseball.",
    "urduExplanation": "بیس بال میں تین اسٹرائیکس پر بیٹر آؤٹ ہو جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_sport_3",
    "category": "Sports",
    "difficulty": "Beginner",
    "question": "In cricket, how many runs are scored if the ball crosses the boundary without bouncing?",
    "urduQuestion": "کرکٹ میں اگر گیند بغیر ٹپ کھائے باؤنڈری پار کر جائے تو کتنے رنز ملتے ہیں؟",
    "options": ["4", "5", "6", "8"],
    "correctAnswer": 2,
    "explanation": "Hitting the ball over the boundary on the full awards 6 runs.",
    "urduExplanation": "گیند بغیر ٹپ کھائے باؤنڈری سے باہر جانے پر 6 رنز ملتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_sport_4",
    "category": "Sports",
    "difficulty": "Beginner",
    "question": "Which sport is played with a shuttlecock (birdie)?",
    "urduQuestion": "کون سا کھیل شٹل کاک کے ساتھ کھیلا جاتا ہے؟",
    "options": ["Tennis", "Badminton", "Table Tennis", "Squash"],
    "correctAnswer": 1,
    "explanation": "Badminton is played using lightweight rackets and a feathered or plastic shuttlecock.",
    "urduExplanation": "بیڈمنٹن کا کھیل ریکیٹ اور شٹل کاک سے کھیلا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_sport_5",
    "category": "Sports",
    "difficulty": "Beginner",
    "question": "How long is a standard Olympic swimming pool?",
    "urduQuestion": "اولمپک سوئمنگ پول کی معیاری لمبائی کتنی ہوتی ہے؟",
    "options": ["25 meters", "50 meters", "75 meters", "100 meters"],
    "correctAnswer": 1,
    "explanation": "An Olympic-size swimming pool is exactly 50 meters long.",
    "urduExplanation": "اولمپک سوئمنگ پول کی لمبائی ٹھیک 50 میٹر ہوتی ہے۔",
    "points": 20
  },
  {
    "id": "quiz_sport_6",
    "category": "Sports",
    "difficulty": "Intermediate",
    "question": "Which country won the first ever FIFA Men's World Cup in 1930?",
    "urduQuestion": "1930 میں پہلا فیفا فٹ بال ورلڈ کپ کس ملک نے جیتا؟",
    "options": ["Brazil", "Argentina", "Uruguay", "Italy"],
    "correctAnswer": 2,
    "explanation": "Uruguay hosted and won the inaugural FIFA World Cup in 1930.",
    "urduExplanation": "یوراگوئے نے 1930 میں پہلا فیفا ورلڈ کپ جیتا تھا۔",
    "points": 25
  },
  {
    "id": "quiz_sport_7",
    "category": "Sports",
    "difficulty": "Intermediate",
    "question": "What is the official distance of an official marathon race?",
    "urduQuestion": "ایک مکمل میراتھن ریس کا باقاعدہ فاصلہ کتنا ہوتا ہے؟",
    "options": ["21.1 km", "42.195 km", "50 km", "35 km"],
    "correctAnswer": 1,
    "explanation": "A marathon race is 42.195 kilometers (26 miles and 385 yards) long.",
    "urduExplanation": "میراتھن کی دوڑ کا باقاعدہ فاصلہ 42.195 کلومیٹر ہوتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_sport_8",
    "category": "Sports",
    "difficulty": "Intermediate",
    "question": "How many colored rings appear on the official Olympic flag?",
    "urduQuestion": "اولمپک کے سرکاری پرچم پر کتنے رنگین دائرے (رنگز) ہوتے ہیں؟",
    "options": ["4", "5", "6", "7"],
    "correctAnswer": 1,
    "explanation": "The Olympic flag has five interlocking rings representing the five inhabited continents.",
    "urduExplanation": "اولمپک پرچم پر دنیا کے 5 براعظموں کی نمائندگی کرنے والے 5 دائرے ہوتے ہیں۔",
    "points": 25
  },
  {
    "id": "quiz_sport_9",
    "category": "Sports",
    "difficulty": "Intermediate",
    "question": "In basketball, how many points is a successful basket made from beyond the three-point arc worth?",
    "urduQuestion": "باسکٹ بال میں تھری پوائنٹ آرک کے پیچھے سے کی جانے والی باسکٹ پر کتنے پوائنٹس ملتے ہیں؟",
    "options": ["2", "3", "4", "1"],
    "correctAnswer": 1,
    "explanation": "Baskets made from beyond the three-point arc score 3 points.",
    "urduExplanation": "تھری پوائنٹ لائن کے پیچھے سے گول کرنے پر 3 پوائنٹس ملتے ہیں۔",
    "points": 25
  },
  {
    "id": "quiz_sport_10",
    "category": "Sports",
    "difficulty": "Intermediate",
    "question": "In which sport might you perform a 'slam dunk'?",
    "urduQuestion": "کس کھیل میں 'سلیم ڈنک' لگایا جاتا ہے؟",
    "options": ["Volleyball", "Basketball", "Handball", "Tennis"],
    "correctAnswer": 1,
    "explanation": "A slam dunk is a scoring shot in basketball where the ball is forced down through the hoop.",
    "urduExplanation": "سلیم ڈنک باسکٹ بال کا ایک طاقتور اور مشہور شاٹ ہے۔",
    "points": 25
  },
  {
    "id": "quiz_sport_11",
    "category": "Sports",
    "difficulty": "Advanced",
    "question": "What is the term for scoring three goals in a single soccer match by one player?",
    "urduQuestion": "فٹ بال کے ایک ہی میچ میں کسی کھلاڑی کے 3 گول کرنے کو کیا کہتے ہیں؟",
    "options": ["Triple Crown", "Hat-trick", "Grand Slam", "Strike"],
    "correctAnswer": 1,
    "explanation": "Scoring three goals in one game by a single player is known as a hat-trick.",
    "urduExplanation": "ایک ہی میچ میں 3 گول کرنے کو ہیٹ ٹرک کہا جاتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_sport_12",
    "category": "Sports",
    "difficulty": "Advanced",
    "question": "In tennis, what is the score called when both players are tied at 40-40?",
    "urduQuestion": "ٹینس میں جب دونوں کھلاڑیوں کا اسکور 40-40 برابر ہو تو اسے کیا کہا جاتا ہے؟",
    "options": ["Advantage", "Deuce", "Tie-break", "Love"],
    "correctAnswer": 1,
    "explanation": "A 40-40 tie in tennis scoring is known as 'Deuce'.",
    "urduExplanation": "ٹینس میں 40-40 کے برابر اسکور کو ڈیس (Deuce) کہا جاتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_sport_13",
    "category": "Sports",
    "difficulty": "Advanced",
    "question": "Which country invented table tennis (ping-pong)?",
    "urduQuestion": "ٹیبل ٹینس (پنگ پانگ) کا کھیل کس ملک نے ایجاد کیا؟",
    "options": ["China", "England", "Japan", "Sweden"],
    "correctAnswer": 1,
    "explanation": "Table tennis originated in Victorian England as an after-dinner parlor game.",
    "urduExplanation": "ٹیبل ٹینس کا آغاز 19 ویں صدی میں انگلینڈ سے ہوا تھا۔",
    "points": 30
  },
  {
    "id": "quiz_sport_14",
    "category": "Sports",
    "difficulty": "Beginner",
    "question": "What color card in soccer results in an immediate ejection from the match?",
    "urduQuestion": "فٹ بال میں کس رنگ کا کارڈ دکھائے جانے پر کھلاڑی میچ سے فوری باہر ہو جاتا ہے؟",
    "options": ["Yellow Card", "Green Card", "Red Card", "Blue Card"],
    "correctAnswer": 2,
    "explanation": "A red card means immediate dismissal from the match.",
    "urduExplanation": "سرخ (ریڈ) کارڈ ملنے پر کھلاڑی کو فوری طور پر گراؤنڈ سے باہر نکال دیا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_sport_15",
    "category": "Sports",
    "difficulty": "Beginner",
    "question": "How many pins are set up at the end of a standard bowling lane?",
    "urduQuestion": "بولنگ کی معیاری لین میں کتنی پنیں رکھی جاتی ہیں؟",
    "options": ["8", "10", "12", "15"],
    "correctAnswer": 1,
    "explanation": "Ten-pin bowling uses exactly 10 wooden pins arranged in a triangle.",
    "urduExplanation": "معیاری بولنگ میں مثلث کی شکل میں 10 پنیں رکھی جاتی ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_sport_16",
    "category": "Sports",
    "difficulty": "Intermediate",
    "question": "Which martial art translates to 'the empty hand' in Japanese?",
    "urduQuestion": "جاپانی زبان میں کس مارشل آرٹ کا مطلب 'خالی ہاتھ' ہے؟",
    "options": ["Judo", "Karate", "Taekwondo", "Aikido"],
    "correctAnswer": 1,
    "explanation": "Karate literally translates to 'kara' (empty) and 'te' (hand).",
    "urduExplanation": "کراٹے کا لفظی ترجمہ 'خالی ہاتھ' ہے۔",
    "points": 25
  },
  {
    "id": "quiz_sport_17",
    "category": "Sports",
    "difficulty": "Intermediate",
    "question": "What is the highest possible break in a standard game of snooker without fouls?",
    "urduQuestion": "اسنوکر کے کھیل میں بغیر فاؤل کے زیادہ سے زیادہ ممکنہ بریک کتنا ہے؟",
    "options": ["140", "147", "155", "160"],
    "correctAnswer": 1,
    "explanation": "A maximum 147 break is made by potting 15 reds with 15 blacks, then all colors.",
    "urduExplanation": "اسنوکر میں بغیر کسی فاؤل کے زیادہ سے زیادہ بریک 147 پوائنٹس کا ہوتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_sport_18",
    "category": "Sports",
    "difficulty": "Advanced",
    "question": "In golf, what is the term for scoring two strokes under par on a hole?",
    "urduQuestion": "گولف میں پار سے 2 اسٹروکس کم اسکور کرنے کو کیا کہتے ہیں؟",
    "options": ["Birdie", "Eagle", "Albatross", "Bogey"],
    "correctAnswer": 1,
    "explanation": "Scoring two strokes under par is called an 'Eagle'.",
    "urduExplanation": "گولف میں پار سے دو اسٹروک کم کھیلنے کو ایگل (Eagle) کہا جاتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_sport_19",
    "category": "Sports",
    "difficulty": "Beginner",
    "question": "How many overs does each team face in a standard T20 cricket match?",
    "urduQuestion": "ٹی 20 کرکٹ میچ میں ہر ٹیم کتنے اوورز کھیلتی ہے؟",
    "options": ["15", "20", "25", "50"],
    "correctAnswer": 1,
    "explanation": "In T20 cricket, each team plays an innings of 20 overs.",
    "urduExplanation": "ٹی 20 کرکٹ میں ہر ٹیم 20 اوورز کھیلتی ہے۔",
    "points": 20
  },
  {
    "id": "quiz_sport_20",
    "category": "Sports",
    "difficulty": "Intermediate",
    "question": "In volleyball, how many times can a team touch the ball before returning it over the net?",
    "urduQuestion": "والی بال میں گیند کو نیٹ کے پار بھیجنے سے پہلے ایک ٹیم زیادہ سے زیادہ کتنی بار چھو سکتی ہے؟",
    "options": ["2", "3", "4", "5"],
    "correctAnswer": 1,
    "explanation": "A team may touch the ball up to 3 times before returning it across the net.",
    "urduExplanation": "والی بال میں گیند واپس بھیجنے سے قبل زیادہ سے زیادہ 3 ٹچز کی اجازت ہوتی ہے۔",
    "points": 25
  },
  {
    "id": "quiz_sport_21",
    "category": "Sports",
    "difficulty": "Beginner",
    "question": "Which surface is the Wimbledon tennis championship played on?",
    "urduQuestion": "ومبلڈن ٹینس چیمپئن شپ کس قسم کی سطح پر کھیلی جاتی ہے؟",
    "options": ["Clay", "Hard Court", "Grass", "Carpet"],
    "correctAnswer": 2,
    "explanation": "Wimbledon is famously played on natural grass courts.",
    "urduExplanation": "ومبلڈن ٹینس کا مقابلہ قدرتی گھاس (Grass) پر کھیلا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_sport_22",
    "category": "Sports",
    "difficulty": "Intermediate",
    "question": "Which nation has won the most FIFA Men's World Cup titles?",
    "urduQuestion": "سب سے زیادہ بار فیفا مینز ورلڈ کپ کس ملک نے جیتا ہے؟",
    "options": ["Germany", "Italy", "Argentina", "Brazil"],
    "correctAnswer": 3,
    "explanation": "Brazil has won the FIFA World Cup 5 times (1958, 1962, 1970, 1994, 2002).",
    "urduExplanation": "برازیل نے اب تک سب سے زیادہ 5 بار فیفا ورلڈ کپ جیتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_sport_23",
    "category": "Sports",
    "difficulty": "Beginner",
    "question": "What piece of equipment protects a cyclist's head during riding?",
    "urduQuestion": "سائیکل چلاتے ہوئے سر کی حفاظت کے لیے کیا پہنا جاتا ہے؟",
    "options": ["Cap", "Helmet", "Headband", "Visor"],
    "correctAnswer": 1,
    "explanation": "A safety helmet protects the head from impacts during cycling.",
    "urduExplanation": "ہیلمٹ سائیکل سوار کے سر کو چوٹ لگنے سے بچاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_sport_24",
    "category": "Sports",
    "difficulty": "Advanced",
    "question": "Which city hosted the 2024 Summer Olympic Games?",
    "urduQuestion": "2024 کے سمر اولمپک کھیلوں کی میزبانی کس شہر نے کی؟",
    "options": ["Tokyo", "London", "Paris", "Los Angeles"],
    "correctAnswer": 2,
    "explanation": "Paris, France hosted the 2024 Summer Olympic Games.",
    "urduExplanation": "2024 کے اولمپک کھیلوں کی میزبانی پیرس (فرانس) نے کی۔",
    "points": 30
  },
  {
    "id": "quiz_sport_25",
    "category": "Sports",
    "difficulty": "Intermediate",
    "question": "In chess, which piece can only move diagonally?",
    "urduQuestion": "شطرنج میں کون سا مہرہ صرف ترچھا (ڈائیگنل) چل سکتا ہے؟",
    "options": ["Rook (Elephant)", "Bishop (Camel)", "Knight (Horse)", "Pawn (Soldier)"],
    "correctAnswer": 1,
    "explanation": "The Bishop moves diagonally across squares of its starting color.",
    "urduExplanation": "شطرنج میں اونٹ (Bishop) ہمیشہ صرف ترچھے خانوں میں چلتا ہے۔",
    "points": 25
  },

  # -------------------------------------------------------------
  # TECHNOLOGY (25 Questions)
  # -------------------------------------------------------------
  {
    "id": "quiz_tech_1",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "What does 'CPU' stand for in computer science?",
    "urduQuestion": "کمپیوٹر سائنس میں 'سی پی یو' کا کیا مطلب ہے؟",
    "options": ["Central Processing Unit", "Central Power Unit", "Core Program User", "Computer Peripheral Unit"],
    "correctAnswer": 0,
    "explanation": "CPU stands for Central Processing Unit, often called the brain of a computer.",
    "urduExplanation": "سی پی یو کا مطلب سینٹرل پروسیسنگ یونٹ ہے جسے کمپیوٹر کا دماغ کہا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_tech_2",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "Which company developed the Android mobile operating system?",
    "urduQuestion": "اینڈرائیڈ موبائل آپریٹنگ سسٹم کس کمپنی نے تیار کیا ہے؟",
    "options": ["Apple", "Microsoft", "Google", "Samsung"],
    "correctAnswer": 2,
    "explanation": "Android was acquired and continuously developed by Google.",
    "urduExplanation": "اینڈرائیڈ آپریٹنگ سسٹم گوگل (Google) نے تیار اور پیش کیا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_tech_3",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "What does 'RAM' stand for in memory specifications?",
    "urduQuestion": "میموری کی اصطلاح میں 'ریم' (RAM) کا کیا مطلب ہے؟",
    "options": ["Random Access Memory", "Read Access Memory", "Rapid Action Module", "Real Audio Memory"],
    "correctAnswer": 0,
    "explanation": "RAM stands for Random Access Memory, temporary high-speed working storage.",
    "urduExplanation": "ریم کا مطلب رینڈم ایکسیس میموری ہے جو عارضی تیز رفتار ڈیٹا محفوظ رکھتی ہے۔",
    "points": 20
  },
  {
    "id": "quiz_tech_4",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "What device is used to connect local computers to the internet wirelessly?",
    "urduQuestion": "کمپیوٹرز اور موبائل فونز کو وائرلیس انٹرنیٹ سے جوڑنے والی ڈیوائس کیا کہلاتی ہے؟",
    "options": ["Wi-Fi Router", "Monitor", "Webcam", "Speaker"],
    "correctAnswer": 0,
    "explanation": "A Wi-Fi router transmits radio waves to provide wireless internet connectivity.",
    "urduExplanation": "وائی فائی راؤٹر وائرلیس طریقے سے انٹرنیٹ سگنلز فراہم کرتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_tech_5",
    "category": "Technology",
    "difficulty": "Intermediate",
    "question": "What is the primary language used to structure web pages on the internet?",
    "urduQuestion": "انٹرنیٹ پر ویب پیجز کی ساخت بنانے کے لیے کون سی بنیادی زبان استعمال ہوتی ہے؟",
    "options": ["HTML", "Python", "SQL", "C++"],
    "correctAnswer": 0,
    "explanation": "HTML (HyperText Markup Language) provides the core structure of web pages.",
    "urduExplanation": "ایچ ٹی ایم ایل (HTML) ویب پیجز کی بنیادی ساخت تیار کرنے کی زبان ہے۔",
    "points": 25
  },
  {
    "id": "quiz_tech_6",
    "category": "Technology",
    "difficulty": "Intermediate",
    "question": "What does the 'S' stand for in the web address prefix 'HTTPS'?",
    "urduQuestion": "ویب ایڈریس 'HTTPS' میں 'S' کا کیا مطلب ہے؟",
    "options": ["Server", "Secure", "Speed", "System"],
    "correctAnswer": 1,
    "explanation": "HTTPS stands for HyperText Transfer Protocol Secure, using encryption to protect data.",
    "urduExplanation": "ایچ ٹی ٹی پی ایس میں ایس کا مطلب 'سیکیور' (محفوظ) ہے جو انکرپشن ظاہر کرتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_tech_7",
    "category": "Technology",
    "difficulty": "Intermediate",
    "question": "What binary digits are used by modern digital computers to represent all data?",
    "urduQuestion": "جدید کمپیوٹر ڈیٹا کی نمائندگی کے لیے کون سے دو بائنری ہندسے استعمال کرتے ہیں؟",
    "options": ["1 and 2", "0 and 1", "0 and 9", "A and B"],
    "correctAnswer": 1,
    "explanation": "Binary code uses 0s and 1s to represent all numbers, text, and computer instructions.",
    "urduExplanation": "کمپیوٹر کی بائنری زبان صرف دو ہندسوں 0 اور 1 پر مشتمل ہوتی ہے۔",
    "points": 25
  },
  {
    "id": "quiz_tech_8",
    "category": "Technology",
    "difficulty": "Intermediate",
    "question": "Which programming language was created by Guido van Rossum in 1991?",
    "urduQuestion": "1991 میں گائیڈو وین روسم نے کون سی مقبول پروگرامنگ زبان ایجاد کی؟",
    "options": ["Java", "Python", "Ruby", "PHP"],
    "correctAnswer": 1,
    "explanation": "Python was created by Guido van Rossum and released in 1991.",
    "urduExplanation": "پائتھن (Python) پروگرامنگ زبان گائیڈو وین روسم نے 1991 میں بنائی تھی۔",
    "points": 25
  },
  {
    "id": "quiz_tech_9",
    "category": "Technology",
    "difficulty": "Advanced",
    "question": "What does 'GPU' stand for, crucial for 3D graphics and artificial intelligence?",
    "urduQuestion": "تھری ڈی گرافکس اور اے آئی کے لیے ضروری 'جی پی یو' کا پورا نام کیا ہے؟",
    "options": ["Graphics Processing Unit", "General Performance Unit", "Global Pixel Utility", "Gaming Port Unit"],
    "correctAnswer": 0,
    "explanation": "GPU stands for Graphics Processing Unit, specialized for parallel rendering and calculations.",
    "urduExplanation": "جی پی یو کا مطلب گرافکس پروسیسنگ یونٹ ہے جو تصاویر اور اے آئی کے حسابات تیز کرتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_tech_10",
    "category": "Technology",
    "difficulty": "Advanced",
    "question": "In networking, what does 'IP' stand for in an IP address?",
    "urduQuestion": "نیٹ ورکنگ میں آئی پی ایڈریس کے اندر 'IP' کا کیا مطلب ہے؟",
    "options": ["Internet Protocol", "Internal Program", "Instant Packet", "Interface Port"],
    "correctAnswer": 0,
    "explanation": "IP stands for Internet Protocol, which routes traffic across connected computer networks.",
    "urduExplanation": "آئی پی کا مطلب 'انٹرنیٹ پروٹوکول' ہے جو ڈیوائسز کے ایڈریس کا تعین کرتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_tech_11",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "What is the shortcut key combination to copy selected text on a Windows computer?",
    "urduQuestion": "ونڈوز کمپیوٹر پر منتخب متن کاپی کرنے کے لیے کون سی شارٹ کٹ کیز استعمال ہوتی ہیں؟",
    "options": ["Ctrl + V", "Ctrl + C", "Ctrl + X", "Ctrl + Z"],
    "correctAnswer": 1,
    "explanation": "Ctrl + C copies the selected item or text to the clipboard.",
    "urduExplanation": "ٹیکسٹ یا فائل کاپی کرنے کے لیے Ctrl + C کا استعمال کیا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_tech_12",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "What does a green padlock icon in the browser address bar typically indicate?",
    "urduQuestion": "ویب براؤزر کے ایڈریس بار میں تالے (Padlock) کا نشان کیا ظاہر کرتا ہے؟",
    "options": ["Website is slow", "Connection is encrypted & secure", "Website is blocked", "File downloading"],
    "correctAnswer": 1,
    "explanation": "A padlock icon signifies an encrypted SSL/TLS connection between browser and website.",
    "urduExplanation": "تالے کا نشان اس بات کی علامت ہے کہ ویب سائٹ کا رابطہ محفوظ اور انکرپٹڈ ہے۔",
    "points": 20
  },
  {
    "id": "quiz_tech_13",
    "category": "Technology",
    "difficulty": "Intermediate",
    "question": "What technology allows short-range wireless communication between devices like wireless headphones and phones?",
    "urduQuestion": "ہیڈ فون اور موبائل کے درمیان قریبی فاصلے پر وائرلیس رابطے کے لیے کون سی ٹیکنالوجی استعمال ہوتی ہے؟",
    "options": ["Bluetooth", "Infrared", "Satellite", "Ethernet"],
    "correctAnswer": 0,
    "explanation": "Bluetooth is a short-range wireless standard operating over 2.4 GHz radio frequencies.",
    "urduExplanation": "بلوٹوتھ (Bluetooth) قریبی فاصلے پر ڈیوائسز کو بغیر تار کے جوڑتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_tech_14",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "How many megabytes (MB) are in one gigabyte (GB) in standard binary decimal units?",
    "urduQuestion": "ایک گیگا بائٹ (GB) میں کتنے میگا بائٹس (MB) ہوتے ہیں؟",
    "options": ["100 MB", "500 MB", "1,000 MB", "10,000 MB"],
    "correctAnswer": 2,
    "explanation": "In standard decimal storage, 1 Gigabyte is equal to 1,000 Megabytes (or 1,024 MB in binary).",
    "urduExplanation": "ایک گیگا بائٹ (GB) میں تقریباً 1000 یا 1024 میگا بائٹس ہوتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_tech_15",
    "category": "Technology",
    "difficulty": "Advanced",
    "question": "What does 'URL' stand for in internet navigation?",
    "urduQuestion": "انٹرنیٹ میں 'URL' کس چیز کا مخفف ہے؟",
    "options": ["Uniform Resource Locator", "Universal Routing Link", "User Record Locator", "Unified Retrieval Link"],
    "correctAnswer": 0,
    "explanation": "URL stands for Uniform Resource Locator, commonly known as a web address.",
    "urduExplanation": "یو آر ایل کا مطلب یونیفارم ریسورس لوکیٹر ہے، یعنی ویب ایڈریس۔",
    "points": 30
  },
  {
    "id": "quiz_tech_16",
    "category": "Technology",
    "difficulty": "Intermediate",
    "question": "Which open-source operating system kernel was created by Linus Torvalds in 1991?",
    "urduQuestion": "1991 میں لائنس ٹوروالڈز نے کون سا اوپن سورس آپریٹنگ سسٹم کرنل بنایا؟",
    "options": ["Windows", "Linux", "macOS", "DOS"],
    "correctAnswer": 1,
    "explanation": "Linus Torvalds developed the Linux kernel, powering servers, Android phones, and supercomputers.",
    "urduExplanation": "لائنس ٹوروالڈز نے لینکس (Linux) آپریٹنگ سسٹم کی بنیاد رکھی۔",
    "points": 25
  },
  {
    "id": "quiz_tech_17",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "What does the cloud icon or 'Cloud Computing' represent?",
    "urduQuestion": "ٹیکنالوجی میں 'کلاؤڈ کمپیوٹنگ' سے کیا مراد ہے؟",
    "options": ["Weather forecasting software", "Storing and accessing data over the internet", "Rain sensing hardware", "Airplane tracking"],
    "correctAnswer": 1,
    "explanation": "Cloud computing means storing and accessing data or programs over the internet instead of a local drive.",
    "urduExplanation": "کلاؤڈ کمپیوٹنگ کا مطلب انٹرنیٹ پر دور دراز محفوظ سرورز پر ڈیٹا محفوظ کرنا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_tech_18",
    "category": "Technology",
    "difficulty": "Intermediate",
    "question": "What type of computer code is designed specifically to detect, isolate, and remove malware?",
    "urduQuestion": "کمپیوٹر سے نقصان دہ وائرس اور میلویئر ختم کرنے والے سافٹ ویئر کو کیا کہتے ہیں؟",
    "options": ["Firewall", "Antivirus", "Spreadsheet", "Debugger"],
    "correctAnswer": 1,
    "explanation": "Antivirus software scans, detects, and removes malicious software threats.",
    "urduExplanation": "اینٹی وائرس سافٹ ویئر کمپیوٹر کو نقصان دہ وائرسز سے محفوظ رکھتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_tech_19",
    "category": "Technology",
    "difficulty": "Advanced",
    "question": "What is the name of the worldwide decentralized network of interconnected computers?",
    "urduQuestion": "دنیا بھر کے کمپیوٹرز کو آپس میں جوڑنے والے عالمی نیٹ ورک کا نام کیا ہے؟",
    "options": ["Intranet", "The Internet", "Ethernet", "Mainframe"],
    "correctAnswer": 1,
    "explanation": "The Internet is the global system of interconnected computer networks.",
    "urduExplanation": "انٹرنیٹ دنیا کا سب سے بڑا گلوبل کمپیوٹر نیٹ ورک ہے۔",
    "points": 30
  },
  {
    "id": "quiz_tech_20",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "Which port standard is now universally used for charging modern smartphones and tablets?",
    "urduQuestion": "آج کل کے جدید اسمارٹ فونز میں چارجنگ کے لیے کون سی یونیورسل پورٹ استعمال ہوتی ہے؟",
    "options": ["VGA", "USB Type-C", "Serial Port", "Parallel Port"],
    "correctAnswer": 1,
    "explanation": "USB Type-C is the reversible standard connector used across modern phones and laptops.",
    "urduExplanation": "یو ایس بی ٹائپ سی (USB Type-C) جدید فونز کی یونیورسل چارجنگ پورٹ ہے۔",
    "points": 20
  },
  {
    "id": "quiz_tech_21",
    "category": "Technology",
    "difficulty": "Intermediate",
    "question": "What does 'PDF' stand for in digital document formats?",
    "urduQuestion": "ڈیجیٹل دستاویزات کے فارمیٹ 'پی ڈی ایف' (PDF) کا پورا نام کیا ہے؟",
    "options": ["Portable Document Format", "Printed Data File", "Public Digital Folder", "Personal Document File"],
    "correctAnswer": 0,
    "explanation": "PDF stands for Portable Document Format, created by Adobe in 1992.",
    "urduExplanation": "پی ڈی ایف کا مطلب پورٹیبل ڈاکیومنٹ فارمیٹ ہے۔",
    "points": 25
  },
  {
    "id": "quiz_tech_22",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "What is the name of the program used to explore websites on the internet (e.g. Chrome, Firefox)?",
    "urduQuestion": "انٹرنیٹ پر ویب سائٹس کھولنے کے لیے استعمال ہونے والے سافٹ ویئر کو کیا کہا جاتا ہے؟",
    "options": ["Web Browser", "Text Editor", "Media Player", "Calculator"],
    "correctAnswer": 0,
    "explanation": "A web browser retrieves, formats, and displays information from the World Wide Web.",
    "urduExplanation": "ویب براؤزر (جیسے کروم یا فائر فاکس) ویب سائٹس کھولنے کے لیے استعمال ہوتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_tech_23",
    "category": "Technology",
    "difficulty": "Advanced",
    "question": "What does 'SSD' stand for in modern high-speed storage drives?",
    "urduQuestion": "جدید تیز رفتار اسٹوریج ڈرائیو میں 'SSD' کا کیا مطلب ہے؟",
    "options": ["Solid State Drive", "Super Speed Disk", "System Storage Device", "Static Silicon Drive"],
    "correctAnswer": 0,
    "explanation": "SSD stands for Solid State Drive, which uses flash memory with no moving parts.",
    "urduExplanation": "ایس ایس ڈی کا مطلب سالڈ اسٹیٹ ڈرائیو ہے جو بغیر کسی گھومنے والے پرزے کے بہت تیز کام کرتی ہے۔",
    "points": 30
  },
  {
    "id": "quiz_tech_24",
    "category": "Technology",
    "difficulty": "Intermediate",
    "question": "What is the process of finding and fixing errors in computer code called?",
    "urduQuestion": "کمپیوٹر پروگرام میں غلطیاں تلاش کرنے اور درست کرنے کے عمل کو کیا کہتے ہیں؟",
    "options": ["Compiling", "Debugging", "Encrypting", "Rendering"],
    "correctAnswer": 1,
    "explanation": "Debugging is the routine process of locating and removing bugs or defects in software code.",
    "urduExplanation": "کوڈ میں سے غلطیاں تلاش کر کے درست کرنے کو ڈی بگنگ (Debugging) کہا جاتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_tech_25",
    "category": "Technology",
    "difficulty": "Beginner",
    "question": "What does a search engine like Google primarily do?",
    "urduQuestion": "گوگل جیسا سرچ انجن بنیادی طور پر کیا کام کرتا ہے؟",
    "options": ["Repairs hardware", "Finds relevant information across the web", "Draws cartoons", "Sends paper letters"],
    "correctAnswer": 1,
    "explanation": "A search engine indexes web pages to help users find relevant information quickly.",
    "urduExplanation": "سرچ انجن انٹرنیٹ پر مطلوبہ معلومات اور ویب سائٹس تلاش کرنے میں مدد دیتا ہے۔",
    "points": 20
  },

  # -------------------------------------------------------------
  # LANGUAGE (25 Questions)
  # -------------------------------------------------------------
  {
    "id": "quiz_lang_1",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "What do we call words that have opposite meanings to each other (e.g., hot and cold)?",
    "urduQuestion": "ان الفاظ کو کیا کہا جاتا ہے جو ایک دوسرے کی ضد یا الٹ ہوں؟",
    "options": ["Synonyms", "Antonyms", "Homophones", "Acronyms"],
    "correctAnswer": 1,
    "explanation": "Antonyms are words with opposite meanings.",
    "urduExplanation": "الٹ یا متضاد معنی رکھنے والے الفاظ کو اینٹونم (Antonym) کہا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_lang_2",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "What do we call words that sound the same but have different spellings and meanings (e.g., hear and here)?",
    "urduQuestion": "ایسے الفاظ جن کی آواز ایک جیسی ہو لیکن ہجے اور معنی مختلف ہوں کیا کہلاتے ہیں؟",
    "options": ["Homophones", "Antonyms", "Verbs", "Pronouns"],
    "correctAnswer": 0,
    "explanation": "Homophones are words that sound identical but differ in meaning or spelling.",
    "urduExplanation": "ہم آواز الفاظ کو ہوموفون (Homophones) کہا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_lang_3",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "How many letters are in the standard modern English alphabet?",
    "urduQuestion": "انگریزی کے حروف تہجی (Alphabet) میں کتنے حروف ہوتے ہیں؟",
    "options": ["24", "26", "28", "30"],
    "correctAnswer": 1,
    "explanation": "The modern English alphabet consists of 26 letters (A to Z).",
    "urduExplanation": "انگریزی حروف تہجی میں A سے Z تک کل 26 حروف ہوتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_lang_4",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "Which of the following is a vowel in the English alphabet?",
    "urduQuestion": "انگریزی حروف میں سے واول (Vowel) حرف کون سا ہے؟",
    "options": ["B", "E", "T", "M"],
    "correctAnswer": 1,
    "explanation": "The English vowels are A, E, I, O, U.",
    "urduExplanation": "انگریزی میں A, E, I, O, U واول حروف ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_lang_5",
    "category": "Language",
    "difficulty": "Intermediate",
    "question": "What part of speech describes an action, state, or occurrence (e.g., run, learn, jump)?",
    "urduQuestion": "گرامر میں وہ لفظ جو کسی کام کے کرنے یا ہونے کو ظاہر کرے کیا کہلاتا ہے؟",
    "options": ["Noun", "Verb", "Adjective", "Preposition"],
    "correctAnswer": 1,
    "explanation": "A verb describes an action, state, or event.",
    "urduExplanation": "کسی کام کے کرنے کو فعل (Verb) کہا جاتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_lang_6",
    "category": "Language",
    "difficulty": "Intermediate",
    "question": "What punctuation mark is placed at the end of an interrogative sentence?",
    "urduQuestion": "سوالیہ جملے کے اختتام پر کون سا نشان لگایا جاتا ہے؟",
    "options": ["Full Stop (.)", "Question Mark (?)", "Comma (,)", "Exclamation Mark (!)"],
    "correctAnswer": 1,
    "explanation": "A question mark (?) ends direct questions.",
    "urduExplanation": "کسی بھی سوالیہ جملے کے آخر میں سوالیہ نشان (?) لگایا جاتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_lang_7",
    "category": "Language",
    "difficulty": "Intermediate",
    "question": "What is the synonym of the word 'Courteous'?",
    "urduQuestion": "لفظ 'Courteous' (خوش اخلاق) کا ہم معنی لفظ کون سا ہے؟",
    "options": ["Rude", "Polite", "Careless", "Angry"],
    "correctAnswer": 1,
    "explanation": "'Polite' and 'courteous' both mean well-mannered and respectful.",
    "urduExplanation": "خوش اخلاق اور باادب کے لیے انگریزی میں 'Polite' استعمال ہوتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_lang_8",
    "category": "Language",
    "difficulty": "Advanced",
    "question": "What is a figure of speech comparing two things using 'like' or 'as' called?",
    "urduQuestion": "انگریزی ادب میں 'like' یا 'as' کے ذریعے دو چیزوں کا موازنہ کرنے کو کیا کہتے ہیں؟",
    "options": ["Metaphor", "Simile", "Hyperbole", "Personification"],
    "correctAnswer": 1,
    "explanation": "A simile explicitly compares two things using words like 'like' or 'as' (e.g. brave as a lion).",
    "urduExplanation": "تشبیہ دینے کے عمل کو انگریزی میں سملی (Simile) کہا جاتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_lang_9",
    "category": "Language",
    "difficulty": "Advanced",
    "question": "What is a palindrome in linguistics?",
    "urduQuestion": "ایسا لفظ یا جملہ جو آگے اور پیچھے دونوں طرف سے ایک جیسا پڑھا جائے کیا کہلاتا ہے؟",
    "options": ["A word read identically forward and backward", "A rhyming poem", "A foreign idiom", "An ancient dialect"],
    "correctAnswer": 0,
    "explanation": "A palindrome reads identically forwards and backwards (e.g., 'radar', 'level', 'kayak').",
    "urduExplanation": "پیلنڈروم (Palindrome) وہ لفظ ہے جو آگے اور پیچھے دونوں طرف سے ہجے میں یکساں ہو۔",
    "points": 30
  },
  {
    "id": "quiz_lang_10",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "What is the plural form of the word 'Child'?",
    "urduQuestion": "لفظ 'Child' کی جمع (Plural) کیا ہے؟",
    "options": ["Childs", "Children", "Childrens", "Childes"],
    "correctAnswer": 1,
    "explanation": "The plural of 'child' is an irregular form: 'children'.",
    "urduExplanation": "انگریزی میں چائلڈ کی جمع چلڈرن (Children) ہوتی ہے۔",
    "points": 20
  },
  {
    "id": "quiz_lang_11",
    "category": "Language",
    "difficulty": "Intermediate",
    "question": "Which word represents a person who writes books, stories, or articles?",
    "urduQuestion": "کتابیں یا مضامین لکھنے والے شخص کو کیا کہتے ہیں؟",
    "options": ["Author", "Auditor", "Actor", "Architect"],
    "correctAnswer": 0,
    "explanation": "An author is the writer of a book, article, or document.",
    "urduExplanation": "کتاب یا مضمون کے مصنف کو آتھر (Author) کہا جاتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_lang_12",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "What is a group of words that expresses a complete thought called?",
    "urduQuestion": "الفاظ کا ایسا مجموعہ جس سے پورا مفہوم سمجھ آئے کیا کہلاتا ہے؟",
    "options": ["Sentence", "Letter", "Prefix", "Syllable"],
    "correctAnswer": 0,
    "explanation": "A sentence is a grammatical unit expressing a complete thought.",
    "urduExplanation": "مکمل مفہوم ادا کرنے والے کلام کو جملہ (Sentence) کہتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_lang_13",
    "category": "Language",
    "difficulty": "Intermediate",
    "question": "What is the past tense of the irregular verb 'Go'?",
    "urduQuestion": "فعل 'Go' کی ماضی کی شکل (Past Tense) کیا ہے؟",
    "options": ["Goed", "Gone", "Went", "Going"],
    "correctAnswer": 2,
    "explanation": "The simple past tense of 'go' is 'went'.",
    "urduExplanation": "انگریزی میں Go کا پاسٹ ٹینز Went ہوتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_lang_14",
    "category": "Language",
    "difficulty": "Advanced",
    "question": "What is the term for a word formed from the initial letters of other words (e.g., NASA)?",
    "urduQuestion": "کئی الفاظ کے پہلے پہلے حروف کو ملا کر بنائے جانے والے لفظ کو کیا کہتے ہیں؟",
    "options": ["Acronym", "Anagram", "Antonym", "Homonym"],
    "correctAnswer": 0,
    "explanation": "An acronym is a word formed from initial letters of a phrase (e.g. UNESCO, NASA).",
    "urduExplanation": "مخفف لفظ کو انگریزی میں ایکرونم (Acronym) کہا جاتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_lang_15",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "Which of these is a noun representing a place?",
    "urduQuestion": "ان میں سے کسی جگہ کی نمائندگی کرنے والا اسم (Noun) کون سا ہے؟",
    "options": ["Quickly", "Library", "Sing", "Bright"],
    "correctAnswer": 1,
    "explanation": "'Library' is a noun designating a physical building or place.",
    "urduExplanation": "لائبریری (کتب خانہ) ایک جگہ کا نام اور اسم ہے۔",
    "points": 20
  },
  {
    "id": "quiz_lang_16",
    "category": "Language",
    "difficulty": "Intermediate",
    "question": "What prefix can be added to 'Happy' to make its opposite meaning?",
    "urduQuestion": "لفظ 'Happy' کے شروع میں کون سا سابقہ (Prefix) لگا کر اس کی ضد بنائی جا سکتی ہے؟",
    "options": ["Dis-", "Un-", "Mis-", "Pre-"],
    "correctAnswer": 1,
    "explanation": "Adding 'Un-' produces 'Unhappy', meaning not happy or sad.",
    "urduExplanation": "ہیپی کے شروع میں Un لگا کر 'Unhappy' بنایا جاتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_lang_17",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "What is the opposite (antonym) of 'Generous'?",
    "urduQuestion": "سخی اور فیاض (Generous) کا الٹ لفظ کون سا ہے؟",
    "options": ["Kind", "Selfish / Stingy", "Helpful", "Honest"],
    "correctAnswer": 1,
    "explanation": "Selfish or stingy is the direct opposite of being generous.",
    "urduExplanation": "سخی کا الٹ کنجوس یا خود غرض (Stingy / Selfish) ہوتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_lang_18",
    "category": "Language",
    "difficulty": "Advanced",
    "question": "What is an anagram of the word 'Listen'?",
    "urduQuestion": "لفظ 'Listen' کے تمام حروف کو نئے انداز میں ترتیب دے کر کون سا نیا لفظ بنتا ہے؟",
    "options": ["Silent", "Loudly", "Nestle", "Tinsel"],
    "correctAnswer": 0,
    "explanation": "'Silent' contains the exact same six letters as 'Listen'.",
    "urduExplanation": "لفظ Listen اور Silent میں بالکل ایک جیسے حروف پائے جاتے ہیں۔",
    "points": 30
  },
  {
    "id": "quiz_lang_19",
    "category": "Language",
    "difficulty": "Intermediate",
    "question": "What word is used to describe a word that modifies or describes a noun (e.g., blue, gentle, fast)?",
    "urduQuestion": "وہ لفظ جو کسی اسم کی خوبی، خامی یا صفت بیان کرے کیا کہلاتا ہے؟",
    "options": ["Adjective", "Conjunction", "Interjection", "Preposition"],
    "correctAnswer": 0,
    "explanation": "An adjective modifies or qualifies a noun or pronoun.",
    "urduExplanation": "اسم کی صفت بیان کرنے والے لفظ کو صفت یا ایڈجیکٹو (Adjective) کہتے ہیں۔",
    "points": 25
  },
  {
    "id": "quiz_lang_20",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "What is the proper greeting in English when meeting someone in the morning?",
    "urduQuestion": "صبح کے وقت ملاقات پر انگریزی میں کیا کہنا مناسب ہے؟",
    "options": ["Good Night", "Good Morning", "Good Evening", "Goodbye"],
    "correctAnswer": 1,
    "explanation": "'Good morning' is the standard polite morning greeting.",
    "urduExplanation": "صبح کے وقت آداب کے لیے 'Good Morning' کہا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_lang_21",
    "category": "Language",
    "difficulty": "Intermediate",
    "question": "What do we call a book that explains the meanings, pronunciations, and origins of words?",
    "urduQuestion": "وہ کتاب جس میں الفاظ کے معنی، تلفظ اور تفصیلات لکھی ہوتی ہیں کیا کہلاتی ہے؟",
    "options": ["Dictionary", "Atlas", "Novel", "Calendar"],
    "correctAnswer": 0,
    "explanation": "A dictionary is a reference book of words and their definitions.",
    "urduExplanation": "لغت یا ڈکشنری (Dictionary) میں الفاظ کے معانی درج ہوتے ہیں۔",
    "points": 25
  },
  {
    "id": "quiz_lang_22",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "Which punctuation mark is used to separate items in a list?",
    "urduQuestion": "فہرست میں مختلف اشیاء کو الگ الگ ظاہر کرنے کے لیے کون سا نشان لگایا جاتا ہے؟",
    "options": ["Comma (,)", "Hyphen (-)", "Slash (/)", "Tilde (~)"],
    "correctAnswer": 0,
    "explanation": "Commas are used to separate items in an enumerated list.",
    "urduExplanation": "اشیاء کے درمیان وقفہ ظاہر کرنے کے لیے کوما (,) لگایا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_lang_23",
    "category": "Language",
    "difficulty": "Advanced",
    "question": "In English grammar, what is an 'oxymoron'?",
    "urduQuestion": "انگریزی میں دو متضاد الفاظ کو ایک ساتھ ملا کر بولنے کی صنعت کو کیا کہتے ہیں؟",
    "options": ["A figure of speech pairing contradictory terms", "A grammatical mistake", "A short summary", "A poem of 14 lines"],
    "correctAnswer": 0,
    "explanation": "An oxymoron combines seemingly contradictory terms (e.g. 'deafening silence', 'clearly confused').",
    "urduExplanation": "دو متضاد الفاظ کے ملاپ جیسے 'خاموش چیخ' کو آکسی مورون (Oxymoron) کہا جاتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_lang_24",
    "category": "Language",
    "difficulty": "Beginner",
    "question": "What is the past tense of 'Eat'?",
    "urduQuestion": "انگریزی فعل 'Eat' (کھانا) کا ماضی کیا ہے؟",
    "options": ["Eated", "Ate", "Eating", "Eats"],
    "correctAnswer": 1,
    "explanation": "The past tense of the verb 'eat' is 'ate'.",
    "urduExplanation": "Eat کا پاسٹ ٹینز Ate ہوتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_lang_25",
    "category": "Language",
    "difficulty": "Intermediate",
    "question": "Which of these words means 'having good manners and treating people gently'?",
    "urduQuestion": "کس لفظ کا مطلب 'اچھے آداب اور نرمی سے پیش آنا' ہے؟",
    "options": ["Grumpy", "Courteous", "Hasty", "Proud"],
    "correctAnswer": 1,
    "explanation": "'Courteous' means showing polite, considerate, and gentle behavior toward others.",
    "urduExplanation": "Courteous کا مطلب شائستہ اور نرم اخلاق ہے۔",
    "points": 25
  },

  # -------------------------------------------------------------
  # ISLAMIC AND MORAL STORIES (25 Questions)
  # -------------------------------------------------------------
  {
    "id": "quiz_moral_1",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "What is the core moral lesson of the famous fable of 'The Tortoise and the Hare'?",
    "urduQuestion": "'کچھوے اور خرگوش' کی مشہور کہانی کا بنیادی اخلاقی سبق کیا ہے؟",
    "options": ["Fastest always wins", "Slow and steady wins the race", "Sleep whenever you feel tired", "Never run outdoors"],
    "correctAnswer": 1,
    "explanation": "Consistency, humility, and steady perseverance triumph over overconfidence and haste.",
    "urduExplanation": "مسلسل محنت اور استقامت ہمیشہ غرور اور جلد بازی پر غالب آتی ہے۔",
    "points": 20
  },
  {
    "id": "quiz_moral_2",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "What noble title was Prophet Muhammad (PBUH) known by in Makkah for his unmatched honesty?",
    "urduQuestion": "مکہ کے لوگ حضور اکرم ﷺ کو سچائی اور دیانت داری کی وجہ سے کس لقب سے پکارتے تھے؟",
    "options": ["Al-Sadiq and Al-Amin", "Al-Hakim", "Al-Mansur", "Al-Rashid"],
    "correctAnswer": 0,
    "explanation": "He was renowned across Arabia as Al-Sadiq (the Truthful) and Al-Amin (the Trustworthy).",
    "urduExplanation": "آپ ﷺ کو اہل مکہ 'الصادق' (سچے) اور 'الامین' (امانت دار) کے لقب سے جانتے تھے۔",
    "points": 20
  },
  {
    "id": "quiz_moral_3",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "Which holy book was revealed to Prophet Dawud (David, peace be upon him)?",
    "urduQuestion": "حضرت داؤد علیہ السلام پر کون سی آسمانی کتاب نازل ہوئی تھی؟",
    "options": ["Tawrat (Torah)", "Zabur (Psalms)", "Injeel (Gospel)", "Quran"],
    "correctAnswer": 1,
    "explanation": "The Zabur was revealed to Prophet Dawud (peace be upon him).",
    "urduExplanation": "حضرت داؤد علیہ السلام پر زبور نازل ہوئی تھی۔",
    "points": 20
  },
  {
    "id": "quiz_moral_4",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "What virtue does the story of the honest woodcutter who dropped his axe into the river teach?",
    "urduQuestion": "دریا میں کلہاڑی گرنے والے دیانت دار لکڑہارے کی کہانی ہمیں کس خوبی کا درس دیتی ہے؟",
    "options": ["Greed pays well", "Honesty is the best policy", "Swimming is dangerous", "Keep extra tools"],
    "correctAnswer": 1,
    "explanation": "By refusing the gold and silver axes and claiming only his own iron axe, honesty was rewarded.",
    "urduExplanation": "سچائی اور دیانت داری سب سے بڑی نیکی اور بہترین حکمت عملی ہے۔",
    "points": 20
  },
  {
    "id": "quiz_moral_5",
    "category": "Islamic and Moral Stories",
    "difficulty": "Intermediate",
    "question": "Which prophet was gifted with the miraculous ability to understand the speech of birds and ants?",
    "urduQuestion": "کس نبی علیہ السلام کو پرندوں اور چیونٹیوں کی بولی سمجھنے کا معجزہ عطا ہوا تھا؟",
    "options": ["Prophet Musa (AS)", "Prophet Sulaiman (AS)", "Prophet Ibrahim (AS)", "Prophet Yunus (AS)"],
    "correctAnswer": 1,
    "explanation": "Prophet Sulaiman (Solomon, AS) was granted wisdom and the ability to understand animals.",
    "urduExplanation": "حضرت سلیمان علیہ السلام پرندوں اور جانوروں کی بولیاں سمجھتے تھے۔",
    "points": 25
  },
  {
    "id": "quiz_moral_6",
    "category": "Islamic and Moral Stories",
    "difficulty": "Intermediate",
    "question": "In the Quranic story of Prophet Yunus (Jonah, AS), what creature sheltered him in the deep ocean?",
    "urduQuestion": "قرآن کریم میں حضرت یونس علیہ السلام کے واقعے میں کس مخلوق نے انہیں اپنے پیٹ میں پناہ دی؟",
    "options": ["Giant Turtle", "Great Whale / Fish", "Dolphin", "Pelican"],
    "correctAnswer": 1,
    "explanation": "Prophet Yunus was swallowed by a great whale and prayed sincerely to Allah for forgiveness.",
    "urduExplanation": "حضرت یونس علیہ السلام کو ایک بڑی مچھلی (حوت) نے نگل لیا تھا۔",
    "points": 25
  },
  {
    "id": "quiz_moral_7",
    "category": "Islamic and Moral Stories",
    "difficulty": "Intermediate",
    "question": "What is the primary moral lesson of the fable 'The Boy Who Cried Wolf'?",
    "urduQuestion": "'بھیڑیا آیا، بھیڑیا آیا' والی کہانی سے ہمیں کیا اخلاقی سبق ملتا ہے؟",
    "options": ["Wolves are friendly", "Liars are not believed even when they tell the truth", "Never tend to sheep alone", "Shouting is good exercise"],
    "correctAnswer": 1,
    "explanation": "Repeated lying destroys trust, so when genuine help is needed, no one believes the liar.",
    "urduExplanation": "بار بار جھوٹ بولنے والے پر اس وقت بھی کوئی یقین نہیں کرتا جب وہ سچ بول رہا ہو۔",
    "points": 25
  },
  {
    "id": "quiz_moral_8",
    "category": "Islamic and Moral Stories",
    "difficulty": "Advanced",
    "question": "Which righteous companion of the Prophet was titled 'Al-Faruq' (the one who distinguishes truth from falsehood)?",
    "urduQuestion": "کس جلیل القدر صحابی کو 'الفاروق' (حق اور باطل میں فرق کرنے والا) کا لقب ملا؟",
    "options": ["Abu Bakr (RA)", "Umar ibn Al-Khattab (RA)", "Uthman ibn Affan (RA)", "Ali ibn Abi Talib (RA)"],
    "correctAnswer": 1,
    "explanation": "Hazrat Umar ibn Al-Khattab (RA) was bestowed the honorary title of Al-Faruq.",
    "urduExplanation": "حضرت عمر بن خطاب رضی اللہ عنہ کو 'الفاروق' کا لقب عطا فرمایا گیا۔",
    "points": 30
  },
  {
    "id": "quiz_moral_9",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "What universal moral duty is emphasized toward one's parents in all heavenly teachings?",
    "urduQuestion": "تمام آسمانی تعلیمات میں والدین کے ساتھ کس سلوک کی سختی سے تاکید کی گئی ہے؟",
    "options": ["Disregard", "Kindness, obedience & utmost respect", "Arguing politely", "Distance"],
    "correctAnswer": 1,
    "explanation": "Treating parents with deep kindness, humility, and gentle respect is an enduring duty.",
    "urduExplanation": "والدین کے ساتھ انتہائی حسن سلوک، ادب اور خدمت کا حکم دیا گیا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_moral_10",
    "category": "Islamic and Moral Stories",
    "difficulty": "Intermediate",
    "question": "Which prophet is remembered for his extraordinary patience (Sabr) during immense hardships?",
    "urduQuestion": "سخت ترین آزمائشوں میں بے مثال صبر کے حوالے سے کس نبی علیہ السلام کا نام تاریخ میں روشن ہے؟",
    "options": ["Prophet Ayyub (Job, AS)", "Prophet Idris (AS)", "Prophet Harun (AS)", "Prophet Yahya (AS)"],
    "correctAnswer": 0,
    "explanation": "Prophet Ayyub (AS) exemplified extraordinary gratitude and patience throughout his trials.",
    "urduExplanation": "حضرت ایوب علیہ السلام نے بیماری اور آزمائش میں بے مثال صبر جمیل کا مظاہرہ کیا۔",
    "points": 25
  },
  {
    "id": "quiz_moral_11",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "What is the virtue of sharing food with hungry neighbors and strangers called in ethics?",
    "urduQuestion": "بھوکوں اور پڑوسیوں کے ساتھ کھانا بانٹنے کی نیکی کو کیا کہا جاتا ہے؟",
    "options": ["Hospitality & Charity (Sadaqah)", "Pride", "Trade", "Hoarding"],
    "correctAnswer": 0,
    "explanation": "Hospitality, kindness, and feeding those in need is celebrated across all moral systems.",
    "urduExplanation": "مہمان نوازی، سخاوت اور ضرورت مندوں کو کھانا کھلانا عظیم عبادت اور نیکی ہے۔",
    "points": 20
  },
  {
    "id": "quiz_moral_12",
    "category": "Islamic and Moral Stories",
    "difficulty": "Advanced",
    "question": "In Islamic history, what great sanctuary did Prophet Ibrahim and his son Ismail (AS) build together in Makkah?",
    "urduQuestion": "حضرت ابراہیم اور حضرت اسماعیل علیہما السلام نے مکہ مکرمہ میں مل کر کس مقدس عمارت کی تعمیر فرمائی؟",
    "options": ["The Holy Kaaba", "Masjid Al-Aqsa", "Masjid An-Nabawi", "Mount Sinai"],
    "correctAnswer": 0,
    "explanation": "Prophet Ibrahim and Ismail (AS) raised the foundations of the Holy Kaaba.",
    "urduExplanation": "حضرت ابراہیم اور حضرت اسماعیل علیہما السلام نے مل کر خانہ کعبہ کی تعمیر فرمائی۔",
    "points": 30
  },
  {
    "id": "quiz_moral_13",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "According to the famous moral tale, how did a thirsty crow drink water from a half-empty pitcher?",
    "urduQuestion": "مشہور کہانی میں پیاسے کوے نے آدھے بھرے گھڑے سے پانی پینے کے لیے کیا تدبیر کی؟",
    "options": ["Broke the pitcher", "Dropped small pebbles until water rose", "Waited for rain", "Flew away sad"],
    "correctAnswer": 1,
    "explanation": "By dropping small pebbles one by one, the water level rose, proving 'where there is a will, there is a way'.",
    "urduExplanation": "کوے نے گھڑے میں کنکر ڈالے جس سے پانی اوپر آ گیا اور اس نے پیاس بجھائی۔",
    "points": 20
  },
  {
    "id": "quiz_moral_14",
    "category": "Islamic and Moral Stories",
    "difficulty": "Intermediate",
    "question": "In the story of Prophet Yusuf (Joseph, AS), what character trait allowed him to forgive his brothers?",
    "urduQuestion": "حضرت یوسف علیہ السلام کے واقعے میں انہوں نے اپنے بھائیوں سے بدلہ لینے کے بجائے کیا طرز عمل اپنایا؟",
    "options": ["Revenge", "Magnificent Forgiveness & Compassion", "Envy", "Punishment"],
    "correctAnswer": 1,
    "explanation": "Prophet Yusuf exemplified unconditional pardon, stating: 'No blame will there be upon you today.'",
    "urduExplanation": "حضرت یوسف علیہ السلام نے اپنے بھائیوں کو معاف فرما کر عفو و درگزر کی اعلیٰ مثال قائم کی۔",
    "points": 25
  },
  {
    "id": "quiz_moral_15",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "What is the greeting of peace taught in Islamic culture that wishes safety upon others?",
    "urduQuestion": "اسلامی تہذیب میں سلامتی اور دعا کا باہمی سلام کیا ہے؟",
    "options": ["As-salamu alaykum (Peace be upon you)", "Bon voyage", "Adios", "Cheers"],
    "correctAnswer": 0,
    "explanation": "As-salamu alaykum is a heartfelt prayer meaning 'Peace be upon you'.",
    "urduExplanation": "السلام علیکم کا مطلب 'تم پر سلامتی ہو' ہے جو آپس میں محبت بڑھاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_moral_16",
    "category": "Islamic and Moral Stories",
    "difficulty": "Advanced",
    "question": "Which beloved grandson of the Prophet is remembered historically for promoting peace and unity among Muslims?",
    "urduQuestion": "حضور اکرم ﷺ کے کس نواسے نے مسلمانوں کے درمیان صلح اور اتحاد قائم کرنے کے لیے عظیم قربانی دی؟",
    "options": ["Hazrat Hasan ibn Ali (RA)", "Hazrat Zayd ibn Haritha (RA)", "Hazrat Bilal (RA)", "Hazrat Salman (RA)"],
    "correctAnswer": 0,
    "explanation": "Hazrat Hasan ibn Ali (RA) made peace to unite the Muslim community and avoid bloodshed.",
    "urduExplanation": "حضرت حسن بن علی رضی اللہ عنہ نے مسلمانوں کے اتحاد اور صلح کے لیے عظیم مثال قائم کی۔",
    "points": 30
  },
  {
    "id": "quiz_moral_17",
    "category": "Islamic and Moral Stories",
    "difficulty": "Intermediate",
    "question": "In moral philosophy, what is the golden rule found in virtually all cultures and faiths?",
    "urduQuestion": "اخلاقیات کا سنہری اصول (Golden Rule) کیا سکھاتا ہے؟",
    "options": ["Take from others before they take from you", "Treat others as you would wish to be treated", "Never speak to strangers", "Keep your wealth secret"],
    "correctAnswer": 1,
    "explanation": "Treating fellow human beings the way you would love to be treated is the cornerstone of moral life.",
    "urduExplanation": "دوسروں کے ساتھ ویسا ہی اچھا سلوک کرو جیسا تم اپنے لیے پسند کرتے ہو۔",
    "points": 25
  },
  {
    "id": "quiz_moral_18",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "What was the very first word of the Holy Quran revealed to Prophet Muhammad (PBUH) in Cave Hira?",
    "urduQuestion": "غار حرا میں نازل ہونے والی قرآن پاک کی پہلی وحی کا پہلا لفظ کیا تھا؟",
    "options": ["Qul (Say)", "Iqra (Read / Proclaim)", "Al-Hamd (Praise)", "Inna (Indeed)"],
    "correctAnswer": 1,
    "explanation": "The first revealed word was 'Iqra', commanding humanity to read, seek knowledge, and learn.",
    "urduExplanation": "پہلا نازل ہونے والا کلمہ 'اقرأ' (پڑھیے) تھا جو علم اور تعلیم کی اہمیت اجاگر کرتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_moral_19",
    "category": "Islamic and Moral Stories",
    "difficulty": "Intermediate",
    "question": "What is the moral teaching behind greeting someone with a gentle smile?",
    "urduQuestion": "مسکرا کر کسی سے ملنے کے بارے میں کیا اخلاقی اور نبوی تعلیم ہے؟",
    "options": ["It wastes time", "Smiling is counted as a form of charity (Sadaqah)", "It shows weakness", "Only smile at relatives"],
    "correctAnswer": 1,
    "explanation": "The Prophet (PBUH) taught that smiling in the face of your brother is considered charity.",
    "urduExplanation": "اپنے بھائی کے سامنے مسکرانا بھی صدقہ اور باعث ثواب ہے۔",
    "points": 25
  },
  {
    "id": "quiz_moral_20",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "In the story of 'The Lion and the Mouse', how did the tiny mouse repay the mighty lion's mercy?",
    "urduQuestion": "'شیر اور چوہے' کی کہانی میں ننھے چوہے نے شیر کے احسان کا بدلہ کیسے چکایا؟",
    "options": ["Brought him meat", "Gnawed through hunter's ropes to set him free", "Dug a deep hole", "Led him to water"],
    "correctAnswer": 1,
    "explanation": "The mouse gnawed through the thick ropes of the hunter's net, proving no act of kindness is wasted.",
    "urduExplanation": "چوہے نے اپنے تیز دانتوں سے شکاری کا جال کاٹ کر شیر کی جان بچائی۔",
    "points": 20
  },
  {
    "id": "quiz_moral_21",
    "category": "Islamic and Moral Stories",
    "difficulty": "Advanced",
    "question": "Which companion was chosen as the first caller to prayer (Mu'azzin) in Islam for his melodious, faithful voice?",
    "urduQuestion": "اسلام کے پہلے مؤذن بننے کا اعزاز کس جلیل القدر صحابی کو حاصل ہوا؟",
    "options": ["Hazrat Bilal ibn Rabah (RA)", "Hazrat Khalid ibn Walid (RA)", "Hazrat Ammar (RA)", "Hazrat Miqdad (RA)"],
    "correctAnswer": 0,
    "explanation": "Hazrat Bilal (RA) was appointed the first Mu'azzin by Prophet Muhammad (PBUH).",
    "urduExplanation": "حضرت بلال حبشی رضی اللہ عنہ کو اسلام کے پہلے مؤذن ہونے کا شرف حاصل ہوا۔",
    "points": 30
  },
  {
    "id": "quiz_moral_22",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "What does being 'Truthful' (Sachai) bring into a person's life and reputation?",
    "urduQuestion": "سچائی اور دیانت داری انسان کی زندگی اور ساکھ میں کیا پیدا کرتی ہے؟",
    "options": ["Trust, peace of mind and honor", "Anxiety", "Financial debt", "Loneliness"],
    "correctAnswer": 0,
    "explanation": "Truthfulness brings lasting peace of mind, self-respect, and community trust.",
    "urduExplanation": "سچائی سے دلی سکون، عزت اور لوگوں کا اعتماد حاصل ہوتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_moral_23",
    "category": "Islamic and Moral Stories",
    "difficulty": "Intermediate",
    "question": "What is the moral wisdom behind fulfilling one's promises (Ahad)?",
    "urduQuestion": "وعدہ پورا کرنے کے بارے میں کیا اخلاقی حکم ہے؟",
    "options": ["Promises should only be kept if convenient", "Keeping promises is a sacred duty and sign of integrity", "Promises expire in 2 days", "Only sign legal contracts"],
    "correctAnswer": 1,
    "explanation": "Keeping covenants and promises is a fundamental sign of integrity, trust, and faith.",
    "urduExplanation": "وعدہ پورا کرنا اعلیٰ کردار کی علامت اور لازمی دینی و اخلاقی فریضہ ہے۔",
    "points": 25
  },
  {
    "id": "quiz_moral_24",
    "category": "Islamic and Moral Stories",
    "difficulty": "Beginner",
    "question": "Why is forgiveness considered superior to revenge in moral teachings?",
    "urduQuestion": "اخلاقیات میں بدلہ لینے سے زیادہ معاف کر دینے کو کیوں فضیلت دی گئی ہے؟",
    "options": ["Forgiveness heals hearts and brings peace", "Revenge is always fun", "Forgiveness costs money", "Courts are closed"],
    "correctAnswer": 0,
    "explanation": "Forgiveness breaks cycles of bitterness, restores inner calm, and earns divine mercy.",
    "urduExplanation": "معاف کر دینے سے دلوں کا بوجھ ہلکا ہوتا ہے اور معاشرے میں امن پھیلتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_moral_25",
    "category": "Islamic and Moral Stories",
    "difficulty": "Advanced",
    "question": "Which historic treaty between Muslims and the Quraysh demonstrated the Prophet's supreme wisdom in diplomacy?",
    "urduQuestion": "قریش اور مسلمانوں کے درمیان ہونے والا کون سا تاریخی معاہدہ حکمت و بصیرت کا شاہکار مانا جاتا ہے؟",
    "options": ["Treaty of Hudaybiyyah", "Charter of Medina", "Pledge of Aqabah", "Treaty of Taif"],
    "correctAnswer": 0,
    "explanation": "The Treaty of Hudaybiyyah opened the doors for peaceful dialogue and spread of understanding.",
    "urduExplanation": "صلح حدیبیہ وہ تاریخی معاہدہ تھا جس نے امن کی راہیں ہموار کیں۔",
    "points": 30
  },

  # -------------------------------------------------------------
  # NATURE (25 Questions)
  # -------------------------------------------------------------
  {
    "id": "quiz_nat_1",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "What process do green plants use to convert sunlight, carbon dioxide, and water into food?",
    "urduQuestion": "پودے سورج کی روشنی اور کاربن ڈائی آکسائیڈ سے اپنی خوراک بنانے کے لیے کون سا عمل کرتے ہیں؟",
    "options": ["Photosynthesis", "Respiration", "Evaporation", "Germination"],
    "correctAnswer": 0,
    "explanation": "Photosynthesis is the biochemical process plants use to produce glucose and oxygen from sunlight.",
    "urduExplanation": "فوٹوسنتھیسز (Photosynthesis) کے ذریعے پودے سورج کی روشنی سے خوراک بناتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_nat_2",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "What is the largest living mammal currently on planet Earth?",
    "urduQuestion": "کرہ ارض پر اس وقت پایا جانے والا سب سے بڑا جاندار کون سا ہے؟",
    "options": ["African Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
    "correctAnswer": 1,
    "explanation": "The Antarctic blue whale can reach lengths over 100 feet and weigh up to 200 tons.",
    "urduExplanation": "نیلی وہیل (Blue Whale) دنیا کی سب سے بڑی جاندار مخلوق ہے۔",
    "points": 20
  },
  {
    "id": "quiz_nat_3",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "Which tree species produces acorns as its seeds?",
    "urduQuestion": "بلوط کا درخت (Oak tree) کس قسم کے بیج پیدا کرتا ہے؟",
    "options": ["Oak Tree", "Pine Tree", "Maple Tree", "Willow Tree"],
    "correctAnswer": 0,
    "explanation": "Acorns are the distinctive nuts and seeds produced by oak trees.",
    "urduExplanation": "بلوط (Oak) کے درخت کے بیجوں کو ایکورن (Acorns) کہا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_nat_4",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "What gas do trees absorb from the atmosphere that helps purify the air we breathe?",
    "urduQuestion": "درخت ہوا کو صاف رکھنے کے لیے ماحول سے کون سی گیس جذب کرتے ہیں؟",
    "options": ["Oxygen", "Carbon Dioxide", "Helium", "Nitrogen"],
    "correctAnswer": 1,
    "explanation": "Trees absorb carbon dioxide and release life-giving oxygen during daylight.",
    "urduExplanation": "درخت کاربن ڈائی آکسائیڈ جذب کر کے ہمیں آکسیجن فراہم کرتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_nat_5",
    "category": "Nature",
    "difficulty": "Intermediate",
    "question": "What is the natural home or environment of a plant, animal, or organism called?",
    "urduQuestion": "کسی جانور یا پودے کے قدرتی مسکن یا رہنے کی جگہ کو کیا کہتے ہیں؟",
    "options": ["Habitat", "Territory", "Aquarium", "Sanctuary"],
    "correctAnswer": 0,
    "explanation": "A habitat is the natural environment in which a species typically lives and thrives.",
    "urduExplanation": "جانوروں اور پودوں کے قدرتی ماحول کو ہیبی ٹیٹ (Habitat) یا مسکن کہا جاتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_nat_6",
    "category": "Nature",
    "difficulty": "Intermediate",
    "question": "What winged insect transforms from a caterpillar inside a chrysalis?",
    "urduQuestion": "کون سا خوبصورت کیڑا تتلی بننے سے پہلے رینگنے والی سنڈی (Caterpillar) ہوتا ہے؟",
    "options": ["Dragonfly", "Butterfly", "Ladybug", "Honeybee"],
    "correctAnswer": 1,
    "explanation": "Butterflies undergo metamorphosis from egg to caterpillar, chrysalis, and winged adult.",
    "urduExplanation": "تتلی اپنے ارتقائی عمل میں پہلے سنڈی ہوتی ہے اور پھر خوبصورت پروں والی تتلی بنتی ہے۔",
    "points": 25
  },
  {
    "id": "quiz_nat_7",
    "category": "Nature",
    "difficulty": "Intermediate",
    "question": "Which bird is famous for its colorful tail feathers that it spreads into a magnificent fan?",
    "urduQuestion": "کون سا پرندہ اپنے رنگ برنگے پروں کو پنکھے کی طرح پھیلا کر رقص کرنے کے لیے مشہور ہے؟",
    "options": ["Swan", "Peacock", "Flamingo", "Parrot"],
    "correctAnswer": 1,
    "explanation": "The male peafowl (peacock) displays breathtaking iridescent eye-spotted tail plumage.",
    "urduExplanation": "مور (Peacock) اپنے خوبصورت اور رنگین پر پھیلا کر رقص کرتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_nat_8",
    "category": "Nature",
    "difficulty": "Advanced",
    "question": "What is the largest living coral reef ecosystem on planet Earth?",
    "urduQuestion": "دنیا کا سب سے بڑا زیر آب مرجانی چٹانوں کا نظام (Coral Reef) کون سا ہے؟",
    "options": ["Great Barrier Reef", "Belize Barrier Reef", "Red Sea Coral Reef", "Florida Reef"],
    "correctAnswer": 0,
    "explanation": "The Great Barrier Reef off Queensland, Australia spans over 2,300 kilometers.",
    "urduExplanation": "آسٹریلیا کی گریٹ بیریئر ریف دنیا کا سب سے بڑا مرجانی نظام ہے۔",
    "points": 30
  },
  {
    "id": "quiz_nat_9",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "How do bees communicate the location of distant flowers to their fellow hive members?",
    "urduQuestion": "شہد کی مکھیاں چھتے میں دوسری مکھیوں کو پھولوں کی سمت کیسے بتاتی ہیں؟",
    "options": ["By making whistling sounds", "Through a special waggle dance", "By blinking their eyes", "By leaving colored pollen trails"],
    "correctAnswer": 1,
    "explanation": "Honeybees perform the famous 'waggle dance' to convey angle and distance to nectar sources.",
    "urduExplanation": "شہد کی مکھیاں ایک خاص ڈانس (Waggle Dance) کے ذریعے پھولوں کی سمت بتاتی ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_nat_10",
    "category": "Nature",
    "difficulty": "Intermediate",
    "question": "What is the fastest land animal in the world, capable of sprinting up to 110 km/h?",
    "urduQuestion": "زمین پر سب سے تیز رفتار دوڑنے والا جانور کون سا ہے؟",
    "options": ["Lion", "Cheetah", "Gazelle", "Horse"],
    "correctAnswer": 1,
    "explanation": "The cheetah can accelerate from 0 to 95 km/h in just 3 seconds.",
    "urduExplanation": "چیتا زمین پر سب سے تیز دوڑنے والا جانور ہے۔",
    "points": 25
  },
  {
    "id": "quiz_nat_11",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "What seasonal sleep state do bears and hedgehogs enter to conserve energy during cold winters?",
    "urduQuestion": "سردیوں میں ریچھ اور دیگر جانور توانائی بچانے کے لیے جو لمبی نیند سوتے ہیں اسے کیا کہتے ہیں؟",
    "options": ["Migration", "Hibernation", "Shedding", "Camouflage"],
    "correctAnswer": 1,
    "explanation": "Hibernation is a state of dormancy and metabolic depression during cold winter months.",
    "urduExplanation": "سردیوں کے موسم کی اس طویل نیند کو ہائبرنیشن (Hibernation) کہا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_nat_12",
    "category": "Nature",
    "difficulty": "Advanced",
    "question": "Which continent is the only natural home of wild kangaroos, koalas, and wombats?",
    "urduQuestion": "کنگرو اور کوآلا قدرتی طور پر صرف کس براعظم میں پائے جاتے ہیں؟",
    "options": ["Africa", "South America", "Australia", "Asia"],
    "correctAnswer": 2,
    "explanation": "Australia is home to unique marsupial wildlife including kangaroos and koalas.",
    "urduExplanation": "کنگرو اور کوآلا جیسے منفرد جانور آسٹریلیا میں پائے جاتے ہیں۔",
    "points": 30
  },
  {
    "id": "quiz_nat_13",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "What type of tree retains its green leaves throughout all four seasons of the year?",
    "urduQuestion": "وہ درخت جو سارا سال ہرے بھرے رہتے ہیں اور پتے نہیں جھاڑتے کیا کہلاتے ہیں؟",
    "options": ["Deciduous", "Evergreen", "Fern", "Moss"],
    "correctAnswer": 1,
    "explanation": "Evergreen trees, such as pines and firs, maintain green foliage year-round.",
    "urduExplanation": "ہمیشہ بہار رہنے والے درختوں کو ایور گرین (Evergreen) کہا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_nat_14",
    "category": "Nature",
    "difficulty": "Intermediate",
    "question": "How do rings inside a cut tree trunk help scientists understand the tree's history?",
    "urduQuestion": "درخت کے تنے میں موجود دائرے (Rings) سائنس دانوں کو کیا معلومات دیتے ہیں؟",
    "options": ["Count the tree's age and historical weather conditions", "Determine the tree's favorite soil", "Count flower blossoms", "Measure bird visits"],
    "correctAnswer": 0,
    "explanation": "Dendrochronology counts growth rings to establish tree age and historical climate patterns.",
    "urduExplanation": "درخت کے دائروں کو گن کر اس کی عمر اور ماضی کے موسم کا اندازہ لگایا جاتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_nat_15",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "Which sweet liquid do flowers produce to attract beneficial insect pollinators?",
    "urduQuestion": "پھول تتلیوں اور مکھیوں کو متوجہ کرنے کے لیے کون سا میٹھا رس بناتے ہیں؟",
    "options": ["Sap", "Nectar", "Chlorophyll", "Honey"],
    "correctAnswer": 1,
    "explanation": "Flowers secrete sugary nectar to reward pollinators like bees, butterflies, and hummingbirds.",
    "urduExplanation": "پھولوں کے میٹھے رس کو نیکٹر (Nectar) کہا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_nat_16",
    "category": "Nature",
    "difficulty": "Advanced",
    "question": "What optical atmospheric phenomenon displays bands of green and violet light in high-latitude night skies?",
    "urduQuestion": "قطبین کے قریب رات کے وقت آسمان پر چمکنے والی رنگین قدرتی روشنیوں کو کیا کہتے ہیں؟",
    "options": ["Aurora Borealis (Northern Lights)", "Solar Eclipse", "Supernova", "Meteor Shower"],
    "correctAnswer": 0,
    "explanation": "Auroras occur when charged solar wind particles collide with Earth's upper atmosphere.",
    "urduExplanation": "شمالی قطب کے آسمان پر چمکنے والی قدرتی روشنیوں کو ارورا بوریالس کہتے ہیں۔",
    "points": 30
  },
  {
    "id": "quiz_nat_17",
    "category": "Nature",
    "difficulty": "Intermediate",
    "question": "What adaptation allows desert camels to endure long journeys without drinking water?",
    "urduQuestion": "اونٹ صحرا کے طویل سفر کے دوران پانی کے بغیر کیسے زندہ رہ سکتا ہے؟",
    "options": ["Stores gallons in ears", "Stores fat reserves in hump that convert to energy", "Breathes underwater", "Swallows sand"],
    "correctAnswer": 1,
    "explanation": "A camel's hump stores fat tissue that metabolizes into water and metabolic energy when needed.",
    "urduExplanation": "اونٹ کے کوہان میں چربی ذخیرہ ہوتی ہے جو ضرورت کے وقت توانائی اور پانی میں بدلتی ہے۔",
    "points": 25
  },
  {
    "id": "quiz_nat_18",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "What flightless aquatic bird native to the Southern Hemisphere is an expert swimmer and diver?",
    "urduQuestion": "برفانی علاقوں میں پایا جانے والا کون سا پرندہ اڑ نہیں سکتا لیکن بہترین تیراک ہے؟",
    "options": ["Penguin", "Seagull", "Pelican", "Duck"],
    "correctAnswer": 0,
    "explanation": "Penguins have flippers instead of wings and excel at underwater swimming.",
    "urduExplanation": "پینگوئن اڑ نہیں سکتے لیکن برفیلے پانیوں میں بہترین تیراکی کرتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_nat_19",
    "category": "Nature",
    "difficulty": "Intermediate",
    "question": "What is the green pigment in plant leaves responsible for absorbing sunlight called?",
    "urduQuestion": "پودوں کے پتوں کا سبز رنگ کس مادے کی وجہ سے ہوتا ہے جو روشنی جذب کرتا ہے؟",
    "options": ["Melanin", "Chlorophyll", "Carotene", "Hemoglobin"],
    "correctAnswer": 1,
    "explanation": "Chlorophyll absorbs red and blue light while reflecting green light.",
    "urduExplanation": "کلوروفل (Chlorophyll) پودوں کے پتوں کو سبز رنگ اور روشنی جذب کرنے کی صلاحیت دیتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_nat_20",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "How many legs does an adult insect typically have?",
    "urduQuestion": "ایک عام کیڑے مکوڑے کی کتنی ٹانگیں ہوتی ہیں؟",
    "options": ["4", "6", "8", "10"],
    "correctAnswer": 1,
    "explanation": "All true insects possess exactly six jointed legs attached to the thorax.",
    "urduExplanation": "تمام کیڑے مکوڑوں کی 6 ٹانگیں ہوتی ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_nat_21",
    "category": "Nature",
    "difficulty": "Intermediate",
    "question": "What animal produces real natural silk to spin its protective cocoon?",
    "urduQuestion": "قدرتی ریشم کس کیڑے کے کوکون سے حاصل کیا جاتا ہے؟",
    "options": ["Silkworm caterpillar", "Honeybee", "Termite", "Scorpion"],
    "correctAnswer": 0,
    "explanation": "The silkworm moth caterpillar spins strong protein filaments to create silk.",
    "urduExplanation": "ریشم کا کیڑا (Silkworm) قدرتی ریشم کے دھاگے بناتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_nat_22",
    "category": "Nature",
    "difficulty": "Advanced",
    "question": "Which massive tree species in California includes the largest single-stem tree on Earth by volume?",
    "urduQuestion": "کیلیفورنیا کے جنگلات میں پایا جانے والا دنیا کا سب سے بڑا اور وزنی درخت کون سا ہے؟",
    "options": ["Giant Sequoia (General Sherman)", "Baobab", "Banyan", "Douglas Fir"],
    "correctAnswer": 0,
    "explanation": "Giant Sequoias, like the General Sherman tree, are the world's largest living trees by volume.",
    "urduExplanation": "جائنٹ سیکوئیا (Giant Sequoia) حجم کے اعتبار سے دنیا کے سب سے بڑے درخت ہیں۔",
    "points": 30
  },
  {
    "id": "quiz_nat_23",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "What is the natural movement of animals from one region to another with the changing seasons called?",
    "urduQuestion": "موسم بدلنے پر پرندوں اور جانوروں کی ایک علاقے سے دوسرے علاقے روانگی کیا کہلاتی ہے؟",
    "options": ["Migration", "Hibernation", "Fossilization", "Evaporation"],
    "correctAnswer": 0,
    "explanation": "Seasonal animal travel between breeding and wintering grounds is known as migration.",
    "urduExplanation": "جانوروں کی موسمی نقل مکانی کو مائیگریشن (Migration) کہا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_nat_24",
    "category": "Nature",
    "difficulty": "Intermediate",
    "question": "Which predatory cat is the largest wild cat species in the world?",
    "urduQuestion": "دنیا میں بلی کے خاندان کا سب سے بڑا اور وزنی جنگلی جانور کون سا ہے؟",
    "options": ["Lion", "Tiger (Siberian/Bengal)", "Jaguar", "Leopard"],
    "correctAnswer": 1,
    "explanation": "Tigers are the largest wild felines, with Siberian tigers weighing up to 300 kilograms.",
    "urduExplanation": "ٹائیگر (شیر/باگھ) جنگلی بلیوں کے خاندان کا سب سے بڑا جانور ہے۔",
    "points": 25
  },
  {
    "id": "quiz_nat_25",
    "category": "Nature",
    "difficulty": "Beginner",
    "question": "What natural structure do honeybees construct out of wax to raise their young and store honey?",
    "urduQuestion": "شہد کی مکھیاں شہد اور اپنے بچوں کی حفاظت کے لیے موم سے کیا بناتی ہیں؟",
    "options": ["Honeycomb", "Nest box", "Web", "Burrow"],
    "correctAnswer": 0,
    "explanation": "Bees build hexagonal wax honeycombs with exceptional structural efficiency.",
    "urduExplanation": "مکھیاں چھتے میں چھ کونوں والے خانوں پر مشتمل ہنی کومب (Honeycomb) بناتی ہیں۔",
    "points": 20
  },

  # -------------------------------------------------------------
  # FUN FACTS (25 Questions)
  # -------------------------------------------------------------
  {
    "id": "quiz_fact_1",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "How many hearts does an octopus have?",
    "urduQuestion": "ایک آکٹوپس (Octopus) کے کتنے دل ہوتے ہیں؟",
    "options": ["1", "2", "3", "4"],
    "correctAnswer": 2,
    "explanation": "An octopus has three hearts: two pump blood to the gills, and one pumps to the body.",
    "urduExplanation": "آکٹوپس کے 3 دل ہوتے ہیں جو خون کی گردش برقرار رکھتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_fact_2",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "What is the only mammal capable of true, sustained powered flight?",
    "urduQuestion": "وہ واحد دودھ پلانے والا جاندار (Mammal) کون سا ہے جو اڑنے کی صلاحیت رکھتا ہے؟",
    "options": ["Flying Squirrel", "Bat", "Sugar Glider", "Colugo"],
    "correctAnswer": 1,
    "explanation": "Bats are the only mammals capable of true powered flight.",
    "urduExplanation": "چمگادڑ واحد ممالیہ جاندار ہے جو باقاعدہ اڑ سکتی ہے۔",
    "points": 20
  },
  {
    "id": "quiz_fact_3",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "Can honey spoil or rot if stored in an airtight jar?",
    "urduQuestion": "اگر شہد کو صاف مرتبان میں بند رکھا جائے تو کیا وہ کبھی خراب ہوتا ہے؟",
    "options": ["Spoils in 1 month", "Spoils in 1 year", "Never spoils; edible for thousands of years", "Spoils in the sun"],
    "correctAnswer": 2,
    "explanation": "Due to its low moisture and natural acidity, properly sealed pure honey never spoils.",
    "urduExplanation": "خالص شہد کبھی خراب نہیں ہوتا اور ہزاروں سال تک محفوظ رہ سکتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_fact_4",
    "category": "Fun Facts",
    "difficulty": "Intermediate",
    "question": "Why are flamingos pink or orange when they mature?",
    "urduQuestion": "فلیمنگو پرندے کا رنگ گلابی یا نارنجی کیوں ہو جاتا ہے؟",
    "options": ["They dye their feathers", "From carotenoid pigments in their diet of shrimp & algae", "From exposure to sunlight", "Genetic mutation"],
    "correctAnswer": 1,
    "explanation": "Flamingos absorb beta-carotene pigments from the microscopic algae and brine shrimp they eat.",
    "urduExplanation": "جھینگوں اور خاص کائی میں موجود قدرتی رنگوں کی وجہ سے فلیمنگو کے پر گلابی ہوتے ہیں۔",
    "points": 25
  },
  {
    "id": "quiz_fact_5",
    "category": "Fun Facts",
    "difficulty": "Intermediate",
    "question": "What animal has fingerprints so identical to humans that they could confuse a crime scene?",
    "urduQuestion": "کس جانور کے انگلیوں کے نشانات (Fingerprints) انسانوں سے اتنے مشابہ ہوتے ہیں کہ پہچاننا مشکل ہو؟",
    "options": ["Koala", "Chimpanzee", "Panda", "Otter"],
    "correctAnswer": 0,
    "explanation": "Koalas have dermatoglyphs (fingerprint ridges) remarkably similar to human fingerprints.",
    "urduExplanation": "کوآلا کے فنگر پرنٹس انسانی انگلیوں کے نشانات سے حیرت انگیز طور پر ملتے ہیں۔",
    "points": 25
  },
  {
    "id": "quiz_fact_6",
    "category": "Fun Facts",
    "difficulty": "Advanced",
    "question": "What color is the blood of a horseshoe crab and an octopus due to copper-based hemocyanin?",
    "urduQuestion": "ہارس شو کریب اور آکٹوپس کے خون کا قدرتی رنگ کیا ہوتا ہے؟",
    "options": ["Red", "Blue", "Green", "Yellow"],
    "correctAnswer": 1,
    "explanation": "Their blood uses copper-rich hemocyanin to carry oxygen, giving it a bright blue color.",
    "urduExplanation": "تانبے (کاپر) پر مبنی کیمیکل کی وجہ سے ان کا خون نیلے رنگ کا ہوتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_fact_7",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "Which bird can fly backwards and even upside down for brief moments?",
    "urduQuestion": "وہ کون سا ننھا پرندہ ہے جو پیچھے کی طرف بھی اڑ سکتا ہے؟",
    "options": ["Sparrow", "Hummingbird", "Pigeon", "Woodpecker"],
    "correctAnswer": 1,
    "explanation": "Hummingbirds have flexible ball-and-socket shoulder joints allowing backward flight.",
    "urduExplanation": "ہمنگ برڈ (Hummingbird) پیچھے کی طرف بھی اڑنے کی حیرت انگیز صلاحیت رکھتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_fact_8",
    "category": "Fun Facts",
    "difficulty": "Intermediate",
    "question": "How long is a day on the planet Venus compared to its year?",
    "urduQuestion": "سیارہ زہرہ (Venus) پر ایک دن اس کے ایک سال سے لمبا کیوں ہوتا ہے؟",
    "options": ["Venus rotates so slowly that one day is longer than its entire orbital year", "Venus never rotates", "Day is 1 hour", "Day is 10 years"],
    "correctAnswer": 0,
    "explanation": "Venus takes 243 Earth days to rotate once, but only 225 Earth days to orbit the Sun.",
    "urduExplanation": "زہرہ اپنے محور پر اتنی سست رفتار گھومتا ہے کہ اس کا ایک دن اس کے پورے سال سے لمبا ہوتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_fact_9",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "What is the only continent on Earth without any native snake species or wild reptiles?",
    "urduQuestion": "دنیا کا وہ واحد براعظم کون سا ہے جہاں کوئی سانپ یا رینگنے والا جانور نہیں رہتا؟",
    "options": ["Europe", "Antarctica", "Australia", "Africa"],
    "correctAnswer": 1,
    "explanation": "Antarctica is too cold for cold-blooded reptiles like snakes to survive.",
    "urduExplanation": "انٹارکٹیکا شدید سردی کی وجہ سے سانپوں اور رینگنے والے جانوروں سے بالکل پاک ہے۔",
    "points": 20
  },
  {
    "id": "quiz_fact_10",
    "category": "Fun Facts",
    "difficulty": "Advanced",
    "question": "What part of an ostrich is larger in volume than its entire brain?",
    "urduQuestion": "شتر مرغ کے جسم کا کون سا عضو اس کے دماغ سے بھی بڑا ہوتا ہے؟",
    "options": ["Its eye", "Its beak", "Its toenail", "Its tongue"],
    "correctAnswer": 0,
    "explanation": "An ostrich's eye is approximately 5 cm in diameter, significantly larger than its brain.",
    "urduExplanation": "شتر مرغ کی آنکھ اس کے پورے دماغ سے بھی بڑی ہوتی ہے۔",
    "points": 30
  },
  {
    "id": "quiz_fact_11",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "How many teeth does an adult human typically have, including wisdom teeth?",
    "urduQuestion": "ایک بالغ انسان کے منہ میں عقل داڑھ سمیت کل کتنے دانت ہوتے ہیں؟",
    "options": ["28", "30", "32", "36"],
    "correctAnswer": 2,
    "explanation": "A full set of adult human teeth consists of 32 teeth (16 upper, 16 lower).",
    "urduExplanation": "بالغ انسان کے مکمل جبڑوں میں 32 دانت ہوتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_fact_12",
    "category": "Fun Facts",
    "difficulty": "Intermediate",
    "question": "What happens to the heart rate of a blue whale when it dives into deep ocean waters?",
    "urduQuestion": "جب نیلی وہیل گہرے سمندر میں غوطہ لگاتی ہے تو اس کے دل کی دھڑکن کتنی کم ہو جاتی ہے؟",
    "options": ["Stops completely", "Slows down to as few as 2 beats per minute", "Speeds up to 200 bpm", "Stays unchanged"],
    "correctAnswer": 1,
    "explanation": "To conserve oxygen on deep dives, a blue whale's heart rate drops to just 2 to 4 bpm.",
    "urduExplanation": "آکسیجن بچانے کے لیے نیلی وہیل کا دل فی منٹ صرف 2 سے 4 بار دھڑکتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_fact_13",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "Which vegetable can bounce like a rubber ball if dropped when fresh and firm?",
    "urduQuestion": "کون سی تازہ بیری یا پھل زمین پر گرنے پر گیند کی طرح اچھلتی ہے؟",
    "options": ["Cranberry", "Tomato", "Cucumber", "Carrot"],
    "correctAnswer": 0,
    "explanation": "Fresh, ripe cranberries contain small air pockets and bounce when dropped.",
    "urduExplanation": "تازہ کرین بیری (Cranberry) ہوا کی پاکٹس کی وجہ سے گیند کی طرح اچھلتی ہے۔",
    "points": 20
  },
  {
    "id": "quiz_fact_14",
    "category": "Fun Facts",
    "difficulty": "Advanced",
    "question": "How long can a garden snail sleep continuously if environmental conditions are dry?",
    "urduQuestion": "خشک موسم میں باغ کا گھونگھا (Snail) زیادہ سے زیادہ کتنے عرصے تک سو سکتا ہے؟",
    "options": ["Up to 3 years", "1 week", "1 month", "10 years"],
    "correctAnswer": 0,
    "explanation": "Snails can estivate (dormant sleep) for up to 3 years awaiting moisture.",
    "urduExplanation": "خشک سالی سے بچنے کے لیے گھونگھا 3 سال تک گہری نیند میں رہ سکتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_fact_15",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "What shape is a honeycomb cell built by honeybees?",
    "urduQuestion": "شہد کی مکھیوں کے چھتے کے خانے کس ہندسی شکل (Shape) کے ہوتے ہیں؟",
    "options": ["Triangle", "Square", "Hexagon (6-sided)", "Circle"],
    "correctAnswer": 2,
    "explanation": "Hexagonal geometry provides maximum storage volume with minimum wax expenditure.",
    "urduExplanation": "شہد کے چھتے کے خانے 6 کونوں والے مسدس (Hexagon) ہوتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_fact_16",
    "category": "Fun Facts",
    "difficulty": "Intermediate",
    "question": "Which animal sleeps with one half of its brain awake and one eye open?",
    "urduQuestion": "کون سا سمندری جاندار خطرات سے چوکنا رہنے کے لیے آدھا دماغ اور ایک آنکھ کھول کر سوتا ہے؟",
    "options": ["Dolphin", "Shark", "Octopus", "Clownfish"],
    "correctAnswer": 0,
    "explanation": "Dolphins use unihemispheric sleep to rest while remaining alert enough to breathe and watch for predators.",
    "urduExplanation": "ڈولفن سانس لینے اور خطرے سے بچنے کے لیے آدھے دماغ سے سوتی ہے۔",
    "points": 25
  },
  {
    "id": "quiz_fact_17",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "What is the hardest natural substance known to science on Earth?",
    "urduQuestion": "زمین پر دریافت ہونے والا سب سے سخت قدرتی مادہ کون سا ہے؟",
    "options": ["Gold", "Diamond", "Iron", "Granite"],
    "correctAnswer": 1,
    "explanation": "Diamond is a crystalline carbon structure rated 10 on the Mohs hardness scale.",
    "urduExplanation": "ہیرا (Diamond) دنیا کا سب سے سخت قدرتی مادہ ہے۔",
    "points": 20
  },
  {
    "id": "quiz_fact_18",
    "category": "Fun Facts",
    "difficulty": "Advanced",
    "question": "Why does hot water freeze faster than cold water under certain specific thermodynamic conditions?",
    "urduQuestion": "کچھ مخصوص حالات میں گرم پانی ٹھنڈے پانی سے پہلے کیوں جم جاتا ہے؟",
    "options": ["Mpemba effect", "Doppler effect", "Coriolis effect", "Greenhouse effect"],
    "correctAnswer": 0,
    "explanation": "The Mpemba effect is the observation that hot water can freeze faster than cold water.",
    "urduExplanation": "اس سائنسی عمل کو 'میمبا ایفیکٹ' (Mpemba Effect) کہا جاتا ہے۔",
    "points": 30
  },
  {
    "id": "quiz_fact_19",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "How many bones are in the body of an adult shark?",
    "urduQuestion": "ایک شارک مچھلی کے جسم میں کتنی ہڈیاں ہوتی ہیں؟",
    "options": ["Zero (its skeleton is made of flexible cartilage)", "100", "206", "500"],
    "correctAnswer": 0,
    "explanation": "Sharks have zero true bones; their skeleton is made entirely of flexible cartilage.",
    "urduExplanation": "شارک میں ہڈیاں نہیں ہوتیں بلکہ اس کا ڈھانچہ لچکدار کرکری ہڈی (Cartilage) پر مشتمل ہوتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_fact_20",
    "category": "Fun Facts",
    "difficulty": "Intermediate",
    "question": "What is the tongue weight of a fully grown adult blue whale approximately equal to?",
    "urduQuestion": "ایک مکمل بڑی نیلی وہیل کی صرف زبان کا وزن کس کے برابر ہوتا ہے؟",
    "options": ["A mouse", "A full-grown elephant", "A bicycle", "A football"],
    "correctAnswer": 1,
    "explanation": "A blue whale's tongue weighs around 2.7 to 4 tons, roughly equal to an entire adult Asian elephant.",
    "urduExplanation": "نیلی وہیل کی زبان کا وزن ایک پورے ہاتھی کے وزن کے برابر ہوتا ہے۔",
    "points": 25
  },
  {
    "id": "quiz_fact_21",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "What is a group of flamingos gathered together called in English?",
    "urduQuestion": "فلیمنگو پرندوں کے جھنڈ کو انگریزی میں کیا کہا جاتا ہے؟",
    "options": ["Flamboyance", "Pack", "Herd", "Pod"],
    "correctAnswer": 0,
    "explanation": "A colorful gathering of flamingos is charmingly called a 'Flamboyance'.",
    "urduExplanation": "فلیمنگو کے غول یا جھنڈ کو 'فلیم بوئنس' (Flamboyance) کہا جاتا ہے۔",
    "points": 20
  },
  {
    "id": "quiz_fact_22",
    "category": "Fun Facts",
    "difficulty": "Advanced",
    "question": "How long does light from the Sun take to reach the Earth across 150 million kilometers?",
    "urduQuestion": "سورج کی روشنی کو زمین تک پہنچنے میں کتنا وقت لگتا ہے؟",
    "options": ["8 minutes and 20 seconds", "1 hour", "Instantaneous", "1 day"],
    "correctAnswer": 0,
    "explanation": "Light traveling at 300,000 km/s takes approximately 8 minutes and 20 seconds to reach Earth.",
    "urduExplanation": "سورج سے زمین تک روشنی پہنچنے میں تقریباً 8 منٹ اور 20 سیکنڈ لگتے ہیں۔",
    "points": 30
  },
  {
    "id": "quiz_fact_23",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "Which animal has the longest neck in the animal kingdom, containing only 7 vertebrae just like humans?",
    "urduQuestion": "جانوروں کی دنیا میں سب سے لمبی گردن کس کی ہوتی ہے جس میں انسان کی طرح صرف 7 مہرے ہوتے ہیں؟",
    "options": ["Giraffe", "Elephant", "Camel", "Horse"],
    "correctAnswer": 0,
    "explanation": "A giraffe's neck can be over 6 feet long, yet contains only 7 neck vertebrae.",
    "urduExplanation": "زرافے کی گردن سب سے لمبی ہوتی ہے جس میں انسان کی طرح 7 مہرے ہوتے ہیں۔",
    "points": 20
  },
  {
    "id": "quiz_fact_24",
    "category": "Fun Facts",
    "difficulty": "Intermediate",
    "question": "Can sea otters hold hands while floating asleep on water?",
    "urduQuestion": "کیا اود بلاؤ (Sea Otters) سوتے ہوئے پانی میں بہنے سے بچنے کے لیے ایک دوسرے کا ہاتھ پکڑتے ہیں؟",
    "options": ["Yes, to prevent drifting apart with ocean currents", "No, they never touch", "Only in aquariums", "Only when eating"],
    "correctAnswer": 0,
    "explanation": "Sea otters hold paws while sleeping on their backs to keep from floating away from each other.",
    "urduExplanation": "جی ہاں، سمندری اود بلاؤ بہہ جانے سے بچنے کے لیے سوتے وقت ہاتھ تھام لیتے ہیں۔",
    "points": 25
  },
  {
    "id": "quiz_fact_25",
    "category": "Fun Facts",
    "difficulty": "Beginner",
    "question": "What is the only fruit that carries its seeds on the outside of its skin?",
    "urduQuestion": "وہ کون سا پھل ہے جس کے بیج اس کے چھلکے کے باہر لگے ہوتے ہیں؟",
    "options": ["Strawberry", "Apple", "Banana", "Watermelon"],
    "correctAnswer": 0,
    "explanation": "Strawberries are unique because their small seeds (achenes) are on the exterior skin.",
    "urduExplanation": "اسٹرابیری وہ واحد پھل ہے جس کے بیج اس کے بیرونی حصے پر ہوتے ہیں۔",
    "points": 20
  }
]

# Read quizDatabase.ts
with open('src/data/quizDatabase.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Convert new_questions to TS syntax
import json

ts_entries = []
for q in new_questions:
    options_str = json.dumps(q["options"], ensure_ascii=False)
    entry = f"""  {{
    id: '{q["id"]}',
    category: '{q["category"]}',
    difficulty: '{q["difficulty"]}',
    question: {json.dumps(q["question"], ensure_ascii=False)},
    urduQuestion: {json.dumps(q["urduQuestion"], ensure_ascii=False)},
    options: {options_str},
    correctAnswer: {q["correctAnswer"]},
    explanation: {json.dumps(q["explanation"], ensure_ascii=False)},
    urduExplanation: {json.dumps(q["urduExplanation"], ensure_ascii=False)},
    points: {q["points"]}
  }}"""
    ts_entries.append(entry)

joined_entries = ",\n" + ",\n".join(ts_entries)

# Insert before closing bracket of ALL_QUIZZES
# Find last occurrence of ];
last_bracket_idx = content.rfind("];")
if last_bracket_idx != -1:
    updated_content = content[:last_bracket_idx] + joined_entries + "\n];\n"
    with open('src/data/quizDatabase.ts', 'w', encoding='utf-8') as f:
        f.write(updated_content)
    print(f"SUCCESS: Added {len(new_questions)} new questions to quizDatabase.ts!")
else:
    print("ERROR: Could not find closing bracket in quizDatabase.ts")
