#!/usr/bin/env python3
"""
Generates 300 Universal Global Quiz Questions for JoyEarn
5 Categories x 3 Difficulty Tiers x 20 Questions each = 300 questions.
Zero regional-specific references; all universal world knowledge.
Every question has 4 unique options (A, B, C, D), correctIndex, points, and a fact.
"""

import json
import os

categories_data = {
    "Geography": {
        "Easy": [
            ("What is the largest ocean on Earth?",
             ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], 2, 20,
             "The Pacific Ocean covers more than 30% of Earth's surface, larger than all land masses combined."),
            ("How many continents exist on planet Earth?",
             ["5 Continents", "6 Continents", "7 Continents", "8 Continents"], 2, 15,
             "The 7 continents are Asia, Africa, North America, South America, Antarctica, Europe, and Australia."),
            ("What is the capital city of France?",
             ["Berlin", "Madrid", "Paris", "Rome"], 2, 15,
             "Paris is known as the City of Light and is home to the Eiffel Tower and Louvre Museum."),
            ("Which is the longest river in the world?",
             ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"], 1, 20,
             "The Nile River flows over 6,650 kilometers northward through northeastern Africa."),
            ("In which continent is the Sahara Desert located?",
             ["Asia", "Africa", "Australia", "South America"], 1, 15,
             "The Sahara is the largest hot desert on Earth, covering approximately 9.2 million square kilometers."),
            ("What is the capital city of Japan?",
             ["Kyoto", "Seoul", "Tokyo", "Osaka"], 2, 15,
             "Tokyo is the most populous metropolitan area in the world with over 37 million residents."),
            ("Which country is famously known as the Land of the Rising Sun?",
             ["China", "Japan", "Norway", "Thailand"], 1, 15,
             "The kanji characters that make up Japan's name (Nippon/Nihon) literally mean sun origin."),
            ("What is the capital city of the United Kingdom?",
             ["Edinburgh", "Dublin", "London", "Cardiff"], 2, 15,
             "London is located on the River Thames and has been a major global settlement for two millennia."),
            ("Which continent is the South Pole located on?",
             ["North America", "Europe", "Antarctica", "Australia"], 2, 20,
             "Antarctica contains the geographic South Pole and is the coldest, windiest, and driest continent."),
            ("What is the smallest continent by land area?",
             ["Europe", "Antarctica", "Australia", "South America"], 2, 15,
             "Australia is the smallest continent and the lowest, flattest, and (apart from Antarctica) driest inhabited continent."),
            ("Which ocean lies between North America and Europe?",
             ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Southern Ocean"], 1, 15,
             "The Atlantic Ocean separates the 'Old World' of Africa and Eurasia from the 'New World' of the Americas."),
            ("What is the capital city of Canada?",
             ["Toronto", "Vancouver", "Ottawa", "Montreal"], 2, 15,
             "Ottawa was chosen as Canada's capital by Queen Victoria in 1857 because of its central location."),
            ("Which country has the largest population in the world?",
             ["United States", "India", "China", "Indonesia"], 1, 20,
             "India surpassed China in 2023 to become the world's most populous nation with over 1.4 billion people."),
            ("What is the capital city of Germany?",
             ["Munich", "Frankfurt", "Berlin", "Hamburg"], 2, 15,
             "Berlin is Germany's largest city and political center, famed for its rich cultural history."),
            ("What natural boundary line divides Earth into Northern and Southern Hemispheres?",
             ["Prime Meridian", "Equator", "Tropic of Cancer", "International Date Line"], 1, 15,
             "The Equator is an imaginary line around the middle of a planet at 0 degrees latitude."),
            ("Which large island country lies off the southeastern coast of mainland Africa?",
             ["Iceland", "Madagascar", "Sri Lanka", "New Zealand"], 1, 20,
             "Madagascar is the world's fourth largest island, renowned for its unique wildlife such as lemurs."),
            ("What is the capital city of Italy?",
             ["Milan", "Venice", "Rome", "Florence"], 2, 15,
             "Rome was the cradle of the ancient Roman Empire and contains the independent Vatican City."),
            ("Which is the largest hot desert in North America?",
             ["Mojave Desert", "Chihuahuan Desert", "Sonoran Desert", "Great Basin Desert"], 1, 20,
             "The Chihuahuan Desert covers about 362,000 square kilometers across the southwestern US and Mexico."),
            ("What is the capital city of Spain?",
             ["Barcelona", "Seville", "Madrid", "Valencia"], 2, 15,
             "Madrid has been the seat of the Spanish monarchy and government since the 16th century."),
            ("Which mountain range forms the natural spine of South America?",
             ["Rocky Mountains", "Alps", "Andes Mountains", "Himalayas"], 2, 20,
             "The Andes is the longest continental mountain range in the world, spanning seven South American countries.")
        ],
        "Medium": [
            ("What is the capital city of Australia?",
             ["Sydney", "Melbourne", "Canberra", "Brisbane"], 2, 35,
             "Canberra was selected as Australia's capital in 1908 as a compromise between Sydney and Melbourne."),
            ("Which mountain range forms the traditional boundary between Europe and Asia?",
             ["Alps", "Ural Mountains", "Carpathians", "Caucasus"], 1, 35,
             "The Ural Mountains run approximately north and south through western Russia."),
            ("What is the largest country in the world by total land area?",
             ["Canada", "United States", "Russia", "China"], 2, 30,
             "Russia encompasses over 17 million square kilometers, covering more than one-eighth of Earth's inhabited land."),
            ("Through which capital city does the River Danube flow alongside Buda and Pest?",
             ["Vienna", "Budapest", "Bratislava", "Belgrade"], 1, 35,
             "Budapest was created in 1873 by the unification of the cities of Buda, Óbuda, and Pest."),
            ("Which narrow strait separates the Iberian Peninsula from Morocco?",
             ["Strait of Hormuz", "Strait of Malacca", "Strait of Gibraltar", "Bosphorus Strait"], 2, 35,
             "The Strait of Gibraltar connects the Atlantic Ocean to the Mediterranean Sea and is 13 km wide at its narrowest point."),
            ("What is the largest island in the world that is not a continent?",
             ["Madagascar", "Greenland", "Borneo", "New Guinea"], 1, 35,
             "Greenland covers about 2.16 million square kilometers and is an autonomous territory of Denmark."),
            ("Which country possesses the longest coastline in the world?",
             ["Australia", "Indonesia", "Canada", "Norway"], 2, 35,
             "Canada has over 243,000 kilometers of coastline bordering the Pacific, Atlantic, and Arctic Oceans."),
            ("What is the capital city of New Zealand?",
             ["Auckland", "Christchurch", "Wellington", "Queenstown"], 2, 30,
             "Wellington is the world's southernmost capital city of a sovereign state."),
            ("Which African river is famous for the majestic Victoria Falls?",
             ["Congo River", "Zambezi River", "Niger River", "Orange River"], 1, 35,
             "Victoria Falls, located on the Zambezi River between Zambia and Zimbabwe, is one of the world's largest waterfalls."),
            ("What is the capital city of Brazil?",
             ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], 2, 35,
             "Brasília was planned and constructed specifically to move the national capital inland in 1960."),
            ("Which lake is the largest freshwater lake by surface area in the world?",
             ["Lake Victoria", "Lake Superior", "Lake Huron", "Lake Michigan"], 1, 35,
             "Lake Superior covers approximately 82,100 square kilometers on the Canada-US border."),
            ("What is the capital city of Egypt?",
             ["Alexandria", "Giza", "Cairo", "Luxor"], 2, 30,
             "Cairo is the largest metropolitan area in the Arab world and sits on the Nile River near the Giza Pyramids."),
            ("Which European country is known for having thousands of fjords along its jagged coastline?",
             ["Sweden", "Norway", "Finland", "Denmark"], 1, 35,
             "Glaciers carved Norway's dramatic steep-walled valleys and coastal fjords during successive ice ages."),
            ("What is the capital city of Argentina?",
             ["Santiago", "Montevideo", "Buenos Aires", "Lima"], 2, 30,
             "Buenos Aires is located on the western shore of the Río de la Plata estuary."),
            ("Which desert is considered the driest non-polar desert in the world?",
             ["Gobi Desert", "Atacama Desert", "Kalahari Desert", "Namib Desert"], 1, 35,
             "Parts of Chile's Atacama Desert have had no recorded rainfall for centuries."),
            ("What is the capital city of South Korea?",
             ["Busan", "Incheon", "Seoul", "Daegu"], 2, 30,
             "Seoul has been the political and economic heart of Korea for more than 600 years."),
            ("Which sea is bordered by Jordan, Israel, and the West Bank, known for high salinity?",
             ["Red Sea", "Dead Sea", "Caspian Sea", "Black Sea"], 1, 30,
             "The Dead Sea's hypersaline water allows people to float effortlessly on its surface."),
            ("What is the capital city of Turkey?",
             ["Istanbul", "Ankara", "Izmir", "Bursa"], 1, 35,
             "Ankara replaced Istanbul as the official capital of the Republic of Turkey in 1923."),
            ("Which is the highest waterfall in the world, dropping over 979 meters?",
             ["Niagara Falls", "Angel Falls", "Iguazu Falls", "Victoria Falls"], 1, 35,
             "Angel Falls in Venezuela cascades uninterrupted from the Auyán-tepui plateau."),
            ("What is the capital city of Switzerland?",
             ["Zurich", "Geneva", "Bern", "Basel"], 2, 35,
             "Bern serves as the federal city and de facto seat of the Swiss government.")
        ],
        "Hard": [
            ("What is the official height of Mount Everest above mean sea level?",
             ["8,611 meters", "8,848.86 meters", "8,586 meters", "8,516 meters"], 1, 55,
             "Mount Everest was jointly remeasured by Nepal and China in 2020 at exactly 8,848.86 meters."),
            ("What is the name of the deepest surveyed oceanic depression on Earth?",
             ["Java Trench", "Puerto Rico Trench", "Challenger Deep in Mariana Trench", "Tonga Trench"], 2, 55,
             "Challenger Deep descends nearly 11,000 meters into the western Pacific Ocean seabed."),
            ("What is the world's largest landlocked sovereign nation by total land area?",
             ["Mongolia", "Kazakhstan", "Bolivia", "Chad"], 1, 55,
             "Kazakhstan spans 2.72 million square kilometers without an outlet to any open ocean."),
            ("Lake Baikal, holding about 20% of Earth's unfrozen surface fresh water, is located in which country?",
             ["Canada", "Finland", "Russia", "Mongolia"], 2, 50,
             "Lake Baikal in southern Siberia is both the deepest (1,642m) and oldest (25 million years) lake on Earth."),
            ("Which country contains the greatest number of natural islands in the world?",
             ["Canada", "Sweden", "Indonesia", "Philippines"], 1, 60,
             "Sweden has over 267,000 natural islands, although only about 1,000 are inhabited."),
            ("What is the capital city of Bhutan?",
             ["Paro", "Punakha", "Thimphu", "Phuntsholing"], 2, 50,
             "Thimphu is nestled in the Himalayas and is one of the few world capitals without traffic lights."),
            ("Which is the world's northernmost permanently inhabited civilian settlement?",
             ["Alert, Canada", "Longyearbyen, Svalbard", "Barrow, Alaska", "Norilsk, Russia"], 1, 60,
             "Longyearbyen on Norway's Svalbard archipelago is the world's northernmost town (above 78° N)."),
            ("What is the official capital city of Nigeria?",
             ["Lagos", "Kano", "Abuja", "Ibadan"], 2, 50,
             "Abuja was purpose-built in the 1980s to replace congested coastal Lagos as the national capital."),
            ("Which two countries share the longest international land border in the world?",
             ["Russia and China", "United States and Canada", "Argentina and Chile", "Kazakhstan and Russia"], 1, 55,
             "The Canada-United States border stretches 8,891 kilometers across land and lakes."),
            ("What is the name of the geographical line of longitude representing 0 degrees?",
             ["International Date Line", "Prime Meridian", "Equator", "Tropic of Capricorn"], 1, 50,
             "The Prime Meridian passes through the Royal Observatory in Greenwich, London."),
            ("Which country completely encloses the independent enclave states of San Marino and Vatican City?",
             ["France", "Spain", "Italy", "Greece"], 2, 50,
             "Italy is home to two separate sovereign enclaves: San Marino and Vatican City."),
            ("What is the capital city of Kazakhstan, renamed back from Nur-Sultan in 2022?",
             ["Almaty", "Astana", "Shymkent", "Aktobe"], 1, 50,
             "Astana was chosen as the capital in 1997 and renamed back to Astana in September 2022."),
            ("Which tectonic plate boundary runs directly through the center of Iceland?",
             ["Eurasian and North American Plates", "Pacific and Nazca Plates", "African and Arabian Plates", "Indian and Australian Plates"], 0, 60,
             "The Mid-Atlantic Ridge splits Iceland as the Eurasian and North American plates pull apart."),
            ("What is the highest capital city in the world at an altitude of approximately 3,640 meters?",
             ["Quito", "Bogotá", "La Paz", "Addis Ababa"], 2, 55,
             "La Paz, Bolivia, is the highest administrative national capital on Earth."),
            ("Which country has the greatest number of official languages recognized in its constitution (11)?",
             ["Switzerland", "Belgium", "South Africa", "India"], 2, 55,
             "South Africa officially recognizes 11 national languages including Zulu, Xhosa, Afrikaans, and English."),
            ("What is the southernmost tip of the South American continent commonly called?",
             ["Cape of Good Hope", "Cape Horn", "Cape Agulhas", "Cape Finisterre"], 1, 55,
             "Cape Horn on Hornos Island in Chile marks the northern boundary of the stormy Drake Passage."),
            ("What is the capital city of Mongolia?",
             ["Darkhan", "Erdenet", "Ulaanbaatar", "Choibalsan"], 2, 50,
             "Ulaanbaatar is the coldest national capital city on Earth by average annual temperature."),
            ("Which body of water connects the Black Sea directly to the Sea of Marmara?",
             ["Dardanelles Strait", "Bosphorus Strait", "Kerch Strait", "Strait of Messina"], 1, 60,
             "The Bosphorus Strait bisects Istanbul, linking the Black Sea with the Sea of Marmara and Mediterranean."),
            ("Which desert is bounded by the Altai Mountains and the Tibetan Plateau across Mongolia and northern China?",
             ["Taklamakan Desert", "Gobi Desert", "Karakum Desert", "Thar Desert"], 1, 55,
             "The Gobi is a cold desert known for dinosaur fossil discoveries and seasonal extremes."),
            ("What is the only nation on Earth that borders both the Caspian Sea and the Persian Gulf?",
             ["Iraq", "Saudi Arabia", "Iran", "Azerbaijan"], 2, 55,
             "Iran occupies the land bridge connecting the inland Caspian Sea in the north to the Persian Gulf in the south.")
        ]
    },
    "Science": {
        "Easy": [
            ("What is the chemical formula for pure drinking water?",
             ["CO2", "H2O", "NaCl", "O2"], 1, 15,
             "Water molecules consist of two hydrogen atoms bonded to one oxygen atom."),
            ("Which gas do green plants absorb from the air during photosynthesis?",
             ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], 1, 15,
             "Plants absorb carbon dioxide and water using sunlight energy to synthesize sugars and release oxygen."),
            ("What is the central core of an atom called?",
             ["Electron", "Nucleus", "Proton", "Neutron"], 1, 15,
             "The nucleus contains an atom's protons and neutrons, packing over 99.9% of its mass."),
            ("What is the boiling point of pure water at standard sea-level atmospheric pressure?",
             ["50°C", "80°C", "100°C", "120°C"], 2, 15,
             "Pure water boils at 100 degrees Celsius (212 degrees Fahrenheit) at 1 atmosphere."),
            ("Which star is at the gravitational center of our Solar System?",
             ["Polaris", "Sirius", "The Sun", "Alpha Centauri"], 2, 15,
             "The Sun contains 99.86% of the mass in the entire Solar System."),
            ("What is the process where liquid water turns into invisible water vapor?",
             ["Condensation", "Evaporation", "Freezing", "Sublimation"], 1, 15,
             "Evaporation occurs when heat energy gives liquid molecules enough speed to escape into the air."),
            ("How many bones are there in an average adult human skeleton?",
             ["186 Bones", "206 Bones", "226 Bones", "256 Bones"], 1, 20,
             "Humans are born with about 270 bones, many of which fuse together as growth finishes."),
            ("What is the closest planet to the Sun in our Solar System?",
             ["Venus", "Earth", "Mercury", "Mars"], 2, 15,
             "Mercury orbits the Sun once every 88 Earth days at an average distance of 58 million km."),
            ("Which gas makes up the majority of the air we breathe (roughly 78%)?",
             ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], 2, 15,
             "Dry air is composed of roughly 78% nitrogen, 21% oxygen, and 1% other trace gases."),
            ("What force keeps objects grounded on Earth's surface?",
             ["Magnetism", "Electricity", "Gravity", "Friction"], 2, 15,
             "Gravity is the universal attractive force exerted by mass on other masses."),
            ("Which organ in the human body is responsible for pumping blood?",
             ["Lungs", "Brain", "Heart", "Liver"], 2, 15,
             "The heart beats approximately 100,000 times each day, circulating vital oxygen and nutrients."),
            ("What state of matter has a definite volume but no fixed shape?",
             ["Solid", "Liquid", "Gas", "Plasma"], 1, 15,
             "A liquid flows to fit the shape of its container while maintaining nearly constant volume."),
            ("Which planet is commonly referred to as the 'Red Planet'?",
             ["Venus", "Jupiter", "Mars", "Saturn"], 2, 15,
             "Mars appears reddish due to iron oxide (rust) widespread across its surface dust."),
            ("What is the green pigment in plant leaves that absorbs sunlight?",
             ["Hemoglobin", "Carotene", "Chlorophyll", "Melanin"], 2, 20,
             "Chlorophyll absorbs blue and red wavelengths of sunlight while reflecting green light."),
            ("How many chambers are there in the human heart?",
             ["2 Chambers", "3 Chambers", "4 Chambers", "5 Chambers"], 2, 15,
             "The human heart has four chambers: two upper atria and two lower ventricles."),
            ("What tool is used to measure ambient atmospheric temperature?",
             ["Barometer", "Thermometer", "Hygrometer", "Anemometer"], 1, 15,
             "Thermometers use liquid expansion or electrical resistance to measure heat energy."),
            ("What is the frozen solid form of water called?",
             ["Steam", "Plasma", "Ice", "Frost"], 2, 15,
             "Water freezes into solid ice at 0 degrees Celsius (32 degrees Fahrenheit)."),
            ("Which natural satellite orbits our home planet Earth?",
             ["Titan", "Europa", "The Moon", "Ganymede"], 2, 15,
             "The Moon is Earth's only natural satellite, orbiting at an average distance of 384,400 km."),
            ("What type of energy is possessed by an object due to its motion?",
             ["Potential Energy", "Chemical Energy", "Kinetic Energy", "Nuclear Energy"], 2, 20,
             "Kinetic energy is calculated as 0.5 * mass * velocity squared."),
            ("Which animal class consists of animals with scales, cold blood, and lungs?",
             ["Amphibians", "Mammals", "Reptiles", "Birds"], 2, 15,
             "Reptiles include snakes, lizards, turtles, and crocodiles with keratinized epidermal scales.")
        ],
        "Medium": [
            ("Which organelle is universally known as the powerhouse of the biological cell?",
             ["Ribosome", "Mitochondria", "Endoplasmic Reticulum", "Golgi Apparatus"], 1, 35,
             "Mitochondria generate adenosine triphosphate (ATP), the primary biochemical energy currency."),
            ("Which metallic element is liquid at standard room temperature and pressure?",
             ["Gallium", "Mercury", "Cesium", "Bromine"], 1, 35,
             "Mercury (symbol Hg) has a freezing point of -38.83°C, remaining liquid at room temperature."),
            ("What is the approximate speed of light in a vacuum?",
             ["150,000 km/s", "300,000 km/s", "450,000 km/s", "600,000 km/s"], 1, 35,
             "Light travels at exactly 299,792 kilometers per second in a vacuum."),
            ("Which planet in our Solar System has the most extensive and visible ring system?",
             ["Jupiter", "Saturn", "Uranus", "Neptune"], 1, 30,
             "Saturn's rings are composed primarily of billions of tiny chunks of water ice and rock."),
            ("What instrument is specifically used to measure electrical current in an active circuit?",
             ["Voltmeter", "Ammeter", "Ohmmeter", "Galvanometer"], 1, 35,
             "An ammeter is connected in series with a circuit to measure electric current in amperes."),
            ("Which human blood cells are responsible for fighting infections and pathogens?",
             ["Red Blood Cells (Erythrocytes)", "Platelets (Thrombocytes)", "White Blood Cells (Leukocytes)", "Plasma cells"], 2, 35,
             "Leukocytes identify, target, and neutralize bacteria, viruses, and foreign organisms."),
            ("What type of lens is thinner in the middle and causes light rays to diverge?",
             ["Convex Lens", "Concave Lens", "Bifocal Lens", "Cylindrical Lens"], 1, 35,
             "A concave lens curves inward, bending parallel light rays outward away from the center."),
            ("What is the chemical symbol for elemental gold on the periodic table?",
             ["Ag", "Au", "Fe", "Pb"], 1, 30,
             "The symbol Au comes from the Latin word 'aurum', meaning shining dawn."),
            ("What is the primary gas that makes up the sun's composition (about 73%)?",
             ["Helium", "Hydrogen", "Oxygen", "Carbon"], 1, 30,
             "The Sun is composed of approximately 73% hydrogen and 25% helium in a superheated plasma state."),
            ("What layer of Earth's atmosphere contains the ozone layer that filters UV radiation?",
             ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], 1, 35,
             "The stratosphere contains the ozone layer, which absorbs harmful ultraviolet radiation."),
            ("Which gland in the human body is known as the master endocrine gland?",
             ["Thyroid Gland", "Adrenal Gland", "Pituitary Gland", "Pancreas"], 2, 35,
             "The pituitary gland produces hormones that control many other hormone-secreting glands."),
            ("What is the name of the process where solid turns directly into gas without melting?",
             ["Condensation", "Sublimation", "Deposition", "Vaporization"], 1, 35,
             "Dry ice (solid carbon dioxide) sublimes directly into gaseous CO2 at room temperature."),
            ("Which subatomic particle has no electric charge (is neutral)?",
             ["Proton", "Neutron", "Electron", "Positron"], 1, 30,
             "Neutrons reside in the atomic nucleus alongside protons and carry a net zero charge."),
            ("What is the largest internal organ in the human body?",
             ["Heart", "Brain", "Liver", "Lungs"], 2, 30,
             "The liver weighs about 1.5 kg and performs over 500 vital biochemical functions."),
            ("What is the unit of electrical resistance in physics?",
             ["Volt", "Ohm", "Watt", "Ampere"], 1, 30,
             "Resistance is measured in ohms (symbol Ω) as defined by Ohm's Law (V = IR)."),
            ("Which vitamin is synthesized in human skin when exposed to sunlight?",
             ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], 3, 30,
             "Sunlight's UVB rays stimulate synthesis of Vitamin D3, essential for bone health and immunity."),
            ("What scale is used to measure earthquake magnitude based on seismic wave energy?",
             ["Beaufort Scale", "Richter / Moment Magnitude Scale", "Mohs Scale", "Kelvin Scale"], 1, 35,
             "Moment Magnitude measures the total energy released at the earthquake's fault rupture."),
            ("What is the pH value of pure distilled water at 25°C?",
             ["pH 5 (Acidic)", "pH 7 (Neutral)", "pH 9 (Basic)", "pH 12 (Alkaline)"], 1, 30,
             "A pH of 7 represents neutral water with equal concentrations of H+ and OH- ions."),
            ("What is the name of the boundary around a black hole beyond which nothing can escape?",
             ["Singularity", "Photon Sphere", "Event Horizon", "Accretion Disk"], 2, 35,
             "The event horizon is the threshold where the gravitational escape velocity exceeds the speed of light."),
            ("Which fundamental force keeps atomic nuclei held tightly together?",
             ["Electromagnetism", "Weak Nuclear Force", "Strong Nuclear Force", "Gravity"], 2, 35,
             "The strong force binds quarks into protons and neutrons, and binds nucleons within the nucleus.")
        ],
        "Hard": [
            ("Which subatomic particle possesses a negative elementary electric charge?",
             ["Proton", "Neutron", "Electron", "Positron"], 2, 50,
             "Electrons were discovered in 1897 by J.J. Thomson in cathode ray experiments."),
            ("What is the hardest naturally occurring mineral on Mohs hardness scale (score 10)?",
             ["Quartz", "Topaz", "Diamond", "Corundum"], 2, 55,
             "Diamond's rigid covalent lattice of carbon atoms makes it the hardest natural mineral known."),
            ("What type of chemical bond involves the mutual sharing of electron pairs between atoms?",
             ["Ionic Bond", "Covalent Bond", "Metallic Bond", "Hydrogen Bond"], 1, 55,
             "Covalent bonds hold molecules like water (H2O) and methane (CH4) together."),
            ("Who formulated the mass-energy equivalence equation E = mc² in 1905?",
             ["Isaac Newton", "Albert Einstein", "Niels Bohr", "Max Planck"], 1, 55,
             "Einstein proved that mass and energy are interchangeable manifestations of the same phenomenon."),
            ("What is the molecular structure of genetic information inside living cells?",
             ["Triple Helix", "Double Helix of DNA", "Beta Sheet", "Single Strand RNA"], 1, 50,
             "The double helix structure of DNA was resolved in 1953 by Watson, Crick, and Franklin."),
            ("What is absolute zero temperature in Celsius, where all classical thermal motion ceases?",
             ["-100°C", "-273.15°C", "-350°C", "-459.67°C"], 1, 60,
             "Absolute zero (0 Kelvin) equals -273.15 degrees Celsius, the thermodynamic lower limit."),
            ("What is the standard unit of frequency equal to one cycle per second?",
             ["Joule", "Pascal", "Hertz", "Tesla"], 2, 50,
             "Hertz (Hz), named after Heinrich Hertz, measures cyclical occurrences per second."),
            ("Which hormone regulates blood glucose levels by allowing cells to absorb sugar?",
             ["Glucagon", "Insulin", "Cortisol", "Adrenaline"], 1, 50,
             "Insulin is produced by the beta cells of the pancreatic islets of Langerhans."),
            ("What particle is the theoretical quantum carrier of the gravitational field?",
             ["Gluon", "Graviton", "Photon", "W Boson"], 1, 60,
             "In theoretical quantum gravity, the graviton is a massless spin-2 boson."),
            ("Which chemical element has the highest melting point of all pure metals (3,422°C)?",
             ["Platinum", "Titanium", "Tungsten (Wolfram)", "Osmium"], 2, 60,
             "Tungsten has the highest melting point of any metal and was historically used in light bulb filaments."),
            ("What is the SI unit of electric capacitance?",
             ["Henry", "Farad", "Coulomb", "Weber"], 1, 55,
             "A capacitor has a capacitance of one farad when one coulomb stores a potential difference of one volt."),
            ("What is the dense collapsed remnant of a massive star supported by degenerate neutrons called?",
             ["White Dwarf", "Neutron Star", "Brown Dwarf", "Red Giant"], 1, 55,
             "Neutron stars have masses around 1.4 times our Sun packed into a sphere just 20 km across."),
            ("Which law of thermodynamics states that the entropy of an isolated system always increases?",
             ["Zeroth Law", "First Law", "Second Law", "Third Law"], 2, 55,
             "The Second Law establishes that natural processes have an irreversible direction toward disorder."),
            ("What type of radioactive decay emits a helium-4 nucleus consisting of two protons and two neutrons?",
             ["Alpha Decay", "Beta-minus Decay", "Beta-plus Decay", "Gamma Emission"], 0, 55,
             "Alpha particles are energetic helium nuclei emitted by heavy unstable elements like uranium."),
            ("What is the most abundant chemical element in the observable universe?",
             ["Helium", "Hydrogen", "Oxygen", "Carbon"], 1, 50,
             "Hydrogen accounts for roughly 75% of the baryonic mass of the observable universe."),
            ("What is the protective sheath that insulates axons and accelerates neural nerve impulses?",
             ["Synapse", "Myelin Sheath", "Dendrite", "Node of Ranvier"], 1, 55,
             "Myelin is a lipid-rich substance produced by Schwann cells and oligodendrocytes."),
            ("What is the name of the effect where light waves shift to lower frequencies as their source moves away?",
             ["Blue Shift", "Redshift", "Photoelectric Effect", "Compton Scattering"], 1, 55,
             "Cosmological redshift provided Edwin Hubble the direct evidence that the universe is expanding."),
            ("What enzyme in saliva begins the chemical digestion of dietary starches into sugars?",
             ["Pepsin", "Amylase", "Lipase", "Trypsin"], 1, 50,
             "Salivary amylase breaks down complex starches into maltose and dextrin right in the mouth."),
            ("What is the principle in quantum mechanics that states position and momentum cannot both be precisely measured?",
             ["Pauli Exclusion Principle", "Heisenberg Uncertainty Principle", "Schrödinger Equation", "Fermi-Dirac Statistics"], 1, 60,
             "Formulated by Werner Heisenberg in 1927, Δx * Δp >= h-bar / 2."),
            ("What is the only known planet in our Solar System with an average density less than liquid water (0.687 g/cm³)?",
             ["Jupiter", "Saturn", "Uranus", "Neptune"], 1, 55,
             "Saturn is so low in average density that it would theoretically float in a sufficiently vast ocean.")
        ]
    },
    "Math": {
        "Easy": [
            ("What is the product of 9 multiplied by 8?",
             ["64", "72", "81", "76"], 1, 15,
             "9 multiplied by 8 equals 72 (9 * 8 = 72)."),
            ("How many straight sides does a regular hexagon have?",
             ["5 Sides", "6 Sides", "7 Sides", "8 Sides"], 1, 15,
             "A hexagon has six straight edges and six interior angles summing to 720 degrees."),
            ("What is 150 divided by 5?",
             ["25", "30", "35", "50"], 1, 15,
             "150 divided by 5 equals 30 (5 * 30 = 150)."),
            ("What is the positive square root of 64?",
             ["6", "7", "8", "9"], 2, 15,
             "Because 8 * 8 = 64, the principal square root is 8."),
            ("If a triangle has interior angles of 60° and 70°, what is the third angle?",
             ["40°", "50°", "60°", "70°"], 1, 20,
             "The sum of angles in any triangle is 180°. 180 - (60 + 70) = 50 degrees."),
            ("What is 25% expressed as a simplified common fraction?",
             ["1/2", "1/3", "1/4", "1/5"], 2, 15,
             "25% equals 25/100, which divides top and bottom by 25 to yield 1/4."),
            ("Which of the following numbers is an even integer?",
             ["17", "23", "34", "49"], 2, 15,
             "Any integer completely divisible by 2 with no remainder is an even number."),
            ("What is the perimeter of a square with a side length of 7 meters?",
             ["21 meters", "28 meters", "49 meters", "14 meters"], 1, 15,
             "The perimeter of a square equals 4 * side length: 4 * 7 = 28 meters."),
            ("What is 12 squared (12 * 12)?",
             ["124", "144", "164", "184"], 1, 15,
             "12 multiplied by 12 equals 144."),
            ("What Roman numeral represents the integer 50?",
             ["X", "L", "C", "D"], 1, 15,
             "In Roman numerals, L denotes 50, C denotes 100, and D denotes 500."),
            ("How many degrees are in a full circular rotation?",
             ["180°", "270°", "360°", "400°"], 2, 15,
             "A full complete circle encompasses 360 degrees."),
            ("What is 3/4 converted into a decimal number?",
             ["0.65", "0.75", "0.80", "0.85"], 1, 15,
             "3 divided by 4 equals 0.75."),
            ("What is the sum of 45 and 55?",
             ["90", "95", "100", "105"], 2, 15,
             "45 + 55 = 100."),
            ("How many edges does a standard 3D cube possess?",
             ["6 Edges", "8 Edges", "12 Edges", "16 Edges"], 2, 20,
             "A cube has 6 square faces, 8 vertices (corners), and 12 straight edges."),
            ("What is 10 cubed (10 * 10 * 10)?",
             ["100", "500", "1,000", "10,000"], 2, 15,
             "10 to the third power equals 1,000."),
            ("What is the arithmetic mean (average) of 10, 20, and 30?",
             ["15", "20", "25", "30"], 1, 15,
             "(10 + 20 + 30) / 3 = 60 / 3 = 20."),
            ("What geometric shape has 3 straight sides and 3 angles?",
             ["Square", "Triangle", "Pentagon", "Rhombus"], 1, 15,
             "A triangle is a closed polygon with exactly three vertices and three sides."),
            ("What is the next number in this sequence: 2, 4, 8, 16, ...?",
             ["24", "30", "32", "36"], 2, 15,
             "Each successive term doubles the previous term: 16 * 2 = 32."),
            ("What is 0 multiplied by any real number?",
             ["The number itself", "0", "1", "Infinity"], 1, 15,
             "By the zero property of multiplication, any number multiplied by zero equals zero."),
            ("What is the name of an angle that measures exactly 90 degrees?",
             ["Acute Angle", "Obtuse Angle", "Right Angle", "Reflex Angle"], 2, 15,
             "A right angle corresponds to one quarter of a full turn (90°).")
        ],
        "Medium": [
            ("What is the value of 2 raised to the 6th power (2^6)?",
             ["32", "64", "128", "256"], 1, 30,
             "2 * 2 * 2 * 2 * 2 * 2 equals 64."),
            ("What is the perimeter of a rectangle with length 12 cm and width 8 cm?",
             ["20 cm", "40 cm", "96 cm", "48 cm"], 1, 35,
             "Perimeter = 2 * (length + width) = 2 * (12 + 8) = 2 * 20 = 40 cm."),
            ("What is the sum of the interior angles of any four-sided polygon (quadrilateral)?",
             ["180°", "270°", "360°", "540°"], 2, 30,
             "Formula: (n - 2) * 180° = (4 - 2) * 180° = 360 degrees."),
            ("Which integer is the only even prime number?",
             ["0", "1", "2", "4"], 2, 30,
             "2 is the smallest prime number and the only one that is an even integer."),
            ("Solve for x in the linear algebraic equation: 3x + 15 = 45.",
             ["x = 8", "x = 10", "x = 12", "x = 15"], 1, 35,
             "Subtract 15 from both sides: 3x = 30; divide by 3: x = 10."),
            ("What is 15 squared (15 * 15)?",
             ["215", "225", "235", "245"], 1, 30,
             "15 multiplied by 15 equals 225."),
            ("What is the statistical median of this data set: 3, 7, 9, 15, 21?",
             ["7", "9", "11", "15"], 1, 35,
             "The median is the exact middle value of an ordered data set: 9."),
            ("What is the area of a circle with a radius of 5 meters (using π ≈ 3.14)?",
             ["31.4 m²", "78.5 m²", "15.7 m²", "50.0 m²"], 1, 35,
             "Area = π * r² = 3.14 * 25 = 78.5 square meters."),
            ("If a product costs $80 after a 20% discount, what was its original price?",
             ["$90", "$100", "$105", "$120"], 1, 35,
             "Price * 0.80 = 80 -> Original Price = 80 / 0.80 = $100."),
            ("What is the greatest common divisor (GCD) of 24 and 36?",
             ["6", "8", "12", "18"], 2, 35,
             "The divisors of 24 and 36 share 12 as their largest common divisor."),
            ("How many degrees are in the sum of interior angles of a 5-sided pentagon?",
             ["360°", "450°", "540°", "720°"], 2, 35,
             "(5 - 2) * 180° = 3 * 180° = 540 degrees."),
            ("What is the slope of the linear equation y = -4x + 9?",
             ["9", "-4", "4", "-9"], 1, 30,
             "In slope-intercept form (y = mx + b), m is the slope: -4."),
            ("What is 7 factorial (7!) equal to?",
             ["720", "5,040", "40,320", "2,520"], 1, 35,
             "7! = 7 * 6 * 5 * 4 * 3 * 2 * 1 = 5,040."),
            ("If you flip a fair two-sided coin 3 times, how many total possible outcomes exist?",
             ["6 outcomes", "8 outcomes", "9 outcomes", "12 outcomes"], 1, 30,
             "2 * 2 * 2 = 2^3 = 8 possible outcomes (HHH, HHT, HTH, etc.)."),
            ("What is the volume of a rectangular prism with dimensions 4 cm by 5 cm by 6 cm?",
             ["60 cm³", "120 cm³", "150 cm³", "240 cm³"], 1, 35,
             "Volume = length * width * height = 4 * 5 * 6 = 120 cubic centimeters."),
            ("What is the hypotenuse of a right-angled triangle with legs of 3 and 4?",
             ["5", "6", "7", "8"], 0, 30,
             "Pythagorean theorem: 3² + 4² = 9 + 16 = 25 -> √25 = 5."),
            ("What is 1/3 plus 1/6 expressed as a simplified fraction?",
             ["2/9", "1/2", "3/6", "2/6"], 1, 30,
             "Convert to common denominator: 2/6 + 1/6 = 3/6 = 1/2."),
            ("Which mathematical term describes a number that cannot be expressed as a ratio of integers?",
             ["Rational", "Irrational", "Complex", "Natural"], 1, 30,
             "Irrational numbers (like √2 and π) have non-repeating, non-terminating decimal expansions."),
            ("What is the sum of the exterior angles of any convex polygon?",
             ["180°", "270°", "360°", "Dependent on side count"], 2, 35,
             "The sum of exterior angles of any convex polygon is always 360 degrees."),
            ("What is the value of x if 2^(x+1) = 32?",
             ["3", "4", "5", "6"], 1, 35,
             "32 = 2^5, so x + 1 = 5 -> x = 4.")
        ],
        "Hard": [
            ("In a right-angled triangle, if the legs are 6 and 8, what is the hypotenuse length?",
             ["9", "10", "12", "14"], 1, 50,
             "By Pythagorean theorem: 6² + 8² = 36 + 64 = 100 -> √100 = 10."),
            ("What is the mathematical constant Pi (π) rounded to four decimal places?",
             ["3.1412", "3.1416", "3.1428", "3.1492"], 1, 50,
             "Pi is approximately 3.14159265..., which rounds to 3.1416."),
            ("What is the derivative of f(x) = 5x³ with respect to x?",
             ["10x²", "15x²", "15x", "5x²"], 1, 55,
             "Using the power rule: d/dx(ax^n) = n * ax^(n-1) -> 3 * 5x² = 15x²."),
            ("What is the sum of the first 10 positive integers (1 + 2 + ... + 10)?",
             ["45", "50", "55", "60"], 2, 50,
             "Formula: n(n + 1)/2 = 10(11)/2 = 110/2 = 55."),
            ("What is the probability of rolling a sum of 7 with two standard six-sided dice?",
             ["1/12", "1/6", "1/8", "5/36"], 1, 55,
             "There are 6 winning combinations: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) out of 36 -> 6/36 = 1/6."),
            ("If log10(x) = 3, what is the value of x?",
             ["30", "100", "1,000", "10,000"], 2, 60,
             "By logarithmic definition, 10^3 = x, so x = 1,000."),
            ("What is the value of the imaginary unit i squared (i²)?",
             ["1", "-1", "0", "undefined"], 1, 50,
             "By definition of complex numbers, the imaginary unit satisfies i² = -1."),
            ("What is the integral of 2x dx with respect to x?",
             ["x² + C", "2x² + C", "x + C", "2 + C"], 0, 55,
             "The anti-derivative of 2x is x² plus an arbitrary constant of integration C."),
            ("What is Euler's identity connecting five fundamental mathematical constants?",
             ["e^(i*pi) + 1 = 0", "e^(pi) = i", "pi * e = 1", "i^e = pi"], 0, 60,
             "Euler's formula e^(i*θ) = cos(θ) + i*sin(θ) at θ = π yields e^(i*π) + 1 = 0."),
            ("How many degrees is an angle of π (pi) radians equivalent to?",
             ["90°", "180°", "270°", "360°"], 1, 50,
             "π radians equals half of a complete rotation, which is exactly 180 degrees."),
            ("In combinatorics, what is 5 choose 2 (5C2)?",
             ["5", "10", "15", "20"], 1, 55,
             "5! / (2! * 3!) = (5 * 4) / 2 = 10."),
            ("What is the determinant of the 2x2 matrix [[3, 2], [1, 4]]?",
             ["10", "12", "14", "8"], 0, 55,
             "Determinant = ad - bc = (3 * 4) - (2 * 1) = 12 - 2 = 10."),
            ("What is the limit of (sin x) / x as x approaches 0?",
             ["0", "1", "Infinity", "Undefined"], 1, 60,
             "The fundamental trigonometric limit establishes lim_{x->0} (sin x)/x = 1."),
            ("In modular arithmetic, what is 37 modulo 7 (37 mod 7)?",
             ["1", "2", "3", "5"], 1, 50,
             "37 divided by 7 equals 5 with a remainder of 2 (7 * 5 + 2 = 37)."),
            ("What is the sum of an infinite geometric series with first term a = 6 and ratio r = 0.5?",
             ["9", "12", "15", "18"], 1, 55,
             "Sum = a / (1 - r) = 6 / (1 - 0.5) = 6 / 0.5 = 12."),
            ("What is the base of the natural logarithm system, constant e, rounded to three decimal places?",
             ["2.142", "2.718", "3.142", "1.618"], 1, 50,
             "Euler's number e is an irrational constant approximately equal to 2.71828..."),
            ("What is the golden ratio constant φ (phi) approximately equal to?",
             ["1.414", "1.618", "1.732", "2.236"], 1, 55,
             "The golden ratio is (1 + √5) / 2 ≈ 1.618033..."),
            ("What is the dot product of vectors u = [2, 3] and v = [4, -1]?",
             ["5", "8", "11", "-5"], 0, 55,
             "Dot product = (2 * 4) + (3 * -1) = 8 - 3 = 5."),
            ("What is the solution to the quadratic equation x² - 9 = 0?",
             ["x = 3 only", "x = -3 only", "x = ±3", "x = 9"], 2, 50,
             "x² = 9 -> x = +3 or x = -3."),
            ("Which famous theorem states that no three positive integers satisfy a^n + b^n = c^n for n > 2?",
             ["Goldbach's Conjecture", "Fermat's Last Theorem", "Riemann Hypothesis", "Poincaré Conjecture"], 1, 60,
             "Stated by Pierre de Fermat in 1637 and famously proved by Andrew Wiles in 1994.")
        ]
    },
    "History": {
        "Easy": [
            ("In which year did World War II officially conclude?",
             ["1918", "1939", "1945", "1953"], 2, 15,
             "World War II officially ended in September 1945 following the surrender of Axis forces."),
            ("Who was the first President of the United States?",
             ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"], 1, 15,
             "George Washington served as the first US President from 1789 to 1797."),
            ("In which country are the ancient Great Pyramids of Giza located?",
             ["Greece", "Egypt", "Iraq", "Jordan"], 1, 15,
             "The Pyramids of Giza were built over 4,500 years ago along the western bank of the Nile."),
            ("Which ancient empire built the Colosseum in Rome?",
             ["Ancient Greece", "Roman Empire", "Ottoman Empire", "Persian Empire"], 1, 15,
             "The Roman Colosseum was completed under Emperor Titus in 80 AD for public spectacles."),
            ("Who was the famous Queen of Ancient Egypt associated with Julius Caesar and Mark Antony?",
             ["Nefertiti", "Cleopatra VII", "Hatshepsut", "Berenice IV"], 1, 15,
             "Cleopatra VII was the last active ruler of the Ptolemaic Kingdom of Egypt."),
            ("In which year did Christopher Columbus first reach the Americas across the Atlantic?",
             ["1453", "1492", "1517", "1588"], 1, 15,
             "Columbus made landfall in the Caribbean on October 12, 1492."),
            ("Which wall dividing an eastern and western European city fell in November 1989?",
             ["Great Wall", "Berlin Wall", "Hadrian's Wall", "Western Wall"], 1, 15,
             "The fall of the Berlin Wall in 1989 marked the reunification of Germany and end of the Cold War."),
            ("What famous ship sank in the North Atlantic in April 1912 on its maiden voyage?",
             ["Lusitania", "Titanic", "Britannic", "Queen Mary"], 1, 15,
             "The RMS Titanic struck an iceberg on the night of April 14, 1912."),
            ("Who was the leader of the civil rights movement who gave the 'I Have a Dream' speech in 1963?",
             ["Malcolm X", "Martin Luther King Jr.", "Frederick Douglass", "Nelson Mandela"], 1, 15,
             "Dr. Martin Luther King Jr. delivered his speech from the Lincoln Memorial in Washington, D.C."),
            ("What ancient wonder was built across northern China to defend against nomadic invasions?",
             ["Colosseum", "Great Wall of China", "Angkor Wat", "Taj Mahal"], 1, 15,
             "The Great Wall of China stretches thousands of kilometers, fortified over multiple dynasties."),
            ("Who was the French military and political leader who crowned himself Emperor in 1804?",
             ["Louis XIV", "Napoleon Bonaparte", "Charles de Gaulle", "Charlemagne"], 1, 15,
             "Napoleon conquered much of continental Europe before his defeat at Waterloo in 1815."),
            ("Which historical era in Europe (14th-17th century) was characterized by a rebirth of art and science?",
             ["Dark Ages", "The Renaissance", "Industrial Revolution", "Bronze Age"], 1, 15,
             "The Renaissance originated in Italian city-states like Florence and reshaped European culture."),
            ("Who painted the famous Renaissance portrait known as the Mona Lisa?",
             ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], 1, 15,
             "Leonardo da Vinci painted the Mona Lisa in Florence in the early 16th century."),
            ("Which global conflict lasted from 1914 to 1918?",
             ["World War I", "World War II", "Seven Years' War", "Crimean War"], 0, 15,
             "World War I ended with the Armistice of 11 November 1918."),
            ("What was the name of the ancient trade route connecting China with the Mediterranean?",
             ["Amber Road", "Spice Route", "Silk Road", "Incense Route"], 2, 20,
             "The Silk Road facilitated commerce, culture, and technological exchange for over a millennium."),
            ("Who was the British Prime Minister who led the United Kingdom during World War II?",
             ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Anthony Eden"], 1, 15,
             "Winston Churchill became Prime Minister in May 1940, rallying Britain with historic speeches."),
            ("Which ancient Greek city was famous for its disciplined military society and warriors?",
             ["Athens", "Sparta", "Corinth", "Thebes"], 1, 15,
             "Sparta was the dominant military power of ancient Greece, renown for its austere training system."),
            ("Who was the first human astronaut to travel into space in April 1961?",
             ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "John Glenn"], 1, 20,
             "Soviet cosmonaut Yuri Gagarin orbited Earth aboard Vostok 1 on April 12, 1961."),
            ("What civilization developed cuneiform script, one of the earliest writing systems?",
             ["Sumerians in Mesopotamia", "Ancient Romans", "Aztecs", "Vikings"], 0, 20,
             "The Sumerians in southern Mesopotamia developed wedge-shaped cuneiform writing around 3200 BC."),
            ("Who invented the movable-type printing press in Europe around 1440?",
             ["Johannes Gutenberg", "Isaac Newton", "Galileo Galilei", "Francis Bacon"], 0, 15,
             "Gutenberg's mechanized movable type revolutionized the spread of knowledge across Europe.")
        ],
        "Medium": [
            ("In which year did the French Revolution begin with the storming of the Bastille?",
             ["1776", "1789", "1804", "1815"], 1, 35,
             "The storming of the Bastille on July 14, 1789 marked the turning point of the French Revolution."),
            ("What historic charter of liberties was signed by King John of England at Runnymede in 1215?",
             ["Bill of Rights", "Magna Carta", "Petition of Right", "Habeas Corpus"], 1, 35,
             "The Magna Carta established the foundational legal principle that nobody, not even the king, is above the law."),
            ("Which treaty signed in 1919 officially ended World War I between Germany and the Allied Powers?",
             ["Treaty of Paris", "Treaty of Versailles", "Treaty of Ghent", "Treaty of Utrecht"], 1, 35,
             "The Treaty of Versailles was negotiated in Paris and signed in the Hall of Mirrors at Versailles."),
            ("Who was the principal author of the United States Declaration of Independence in 1776?",
             ["Benjamin Franklin", "Thomas Jefferson", "John Adams", "Alexander Hamilton"], 1, 35,
             "Thomas Jefferson drafted the historic document proclaiming unalienable human rights."),
            ("In which year did the Ottoman conquest of Constantinople take place under Sultan Mehmed II?",
             ["1299", "1453", "1517", "1529"], 1, 35,
             "The fall of Constantinople in 1453 brought an end to the Byzantine Empire."),
            ("Which Roman general and statesman was assassinated on the Ides of March (March 15) in 44 BC?",
             ["Mark Antony", "Julius Caesar", "Pompey the Great", "Scipio Africanus"], 1, 30,
             "Julius Caesar was assassinated in the Roman Senate by a conspiracy of senators led by Brutus and Cassius."),
            ("Which ancient civilization built the terraced mountain citadel of Machu Picchu in Peru?",
             ["Aztec Empire", "Maya Civilization", "Inca Empire", "Olmec Civilization"], 2, 35,
             "Machu Picchu was constructed around 1450 by the Inca Empire high in the Andes mountains."),
            ("Who was the first emperor of a unified China, who ordered the creation of the Terracotta Army?",
             ["Han Wudi", "Qin Shi Huang", "Kublai Khan", "Sun Yat-sen"], 1, 35,
             "Qin Shi Huang standardized weights, currency, and script upon unifying China in 221 BC."),
            ("What 1863 executive proclamation issued by Abraham Lincoln declared enslaved people in rebel states free?",
             ["Gettysburg Address", "Emancipation Proclamation", "Fourteenth Amendment", "Civil Rights Act"], 1, 35,
             "The Emancipation Proclamation transformed the American Civil War into a direct fight to end slavery."),
            ("Who was the famous Macedonian king who conquered the Persian Empire by age 30?",
             ["Philip II", "Alexander the Great", "Pericles", "Pyrrhus"], 1, 30,
             "Alexander the Great undefeated in battle created an empire stretching from Greece to northwestern India."),
            ("In what year did the Apollo 11 mission successfully land the first humans on the Moon?",
             ["1965", "1969", "1972", "1975"], 1, 30,
             "On July 20, 1969, Neil Armstrong and Buzz Aldrin stepped onto the lunar surface in the Sea of Tranquility."),
            ("Which Portuguese explorer was the first European to sail directly from Europe to India via the Cape of Good Hope?",
             ["Ferdinand Magellan", "Vasco da Gama", "Bartolomeu Dias", "Prince Henry the Navigator"], 1, 35,
             "Vasco da Gama arrived in Calicut (Kozhikode), India, in May 1498."),
            ("What deadly pandemic caused by Yersinia pestis devastated Europe between 1346 and 1353?",
             ["Spanish Flu", "The Black Death", "Cholera Pandemic", "Antonine Plague"], 1, 30,
             "The Black Death is estimated to have killed 30% to 60% of the entire population of Europe."),
            ("Who was the South African anti-apartheid leader who was inaugurated as President in 1994?",
             ["Desmond Tutu", "Nelson Mandela", "Steve Biko", "Oliver Tambo"], 1, 30,
             "After spending 27 years in prison, Nelson Mandela won South Africa's first fully democratic election."),
            ("What ancient Babylonian king is famous for his comprehensive written legal code dating to 1750 BC?",
             ["Nebuchadnezzar", "Hammurabi", "Gilgamesh", "Sargon"], 1, 35,
             "The Code of Hammurabi contained 282 laws inscribed on a monumental diorite stele."),
            ("Which battle in 1815 marked the final defeat of French Emperor Napoleon Bonaparte?",
             ["Battle of Austerlitz", "Battle of Waterloo", "Battle of Leipzig", "Battle of Trafalgar"], 1, 35,
             "Napoleon was defeated in Belgium by Anglo-Allied and Prussian forces led by the Duke of Wellington and Blücher."),
            ("Who was the Polish astronomer who proposed the heliocentric model of the Solar System in 1543?",
             ["Tycho Brahe", "Nicolaus Copernicus", "Johannes Kepler", "Galileo Galilei"], 1, 35,
             "Copernicus published 'De revolutionibus orbium coelestium' arguing planets orbit the Sun."),
            ("What empire was ruled by Suleiman the Magnificent during its golden age in the 16th century?",
             ["Persian Empire", "Ottoman Empire", "Mughal Empire", "Byzantine Empire"], 1, 35,
             "Suleiman expanded Ottoman rule across southeastern Europe, western Asia, and north Africa."),
            ("What major international peacekeeping organization was founded in October 1945 following World War II?",
             ["League of Nations", "United Nations", "NATO", "European Union"], 1, 30,
             "The United Nations was established in San Francisco to foster international cooperation and prevent world wars."),
            ("Which Russian Tsar modernized the country and founded a new imperial capital on the Baltic Sea in 1703?",
             ["Ivan the Terrible", "Peter the Great", "Nicholas II", "Alexander II"], 1, 35,
             "Peter the Great founded Saint Petersburg as a European-oriented window to the west.")
        ],
        "Hard": [
            ("Which battle in 1066 resulted in the Norman conquest of England by William the Conqueror?",
             ["Battle of Agincourt", "Battle of Hastings", "Battle of Stamford Bridge", "Battle of Bannockburn"], 1, 55,
             "On October 14, 1066, Duke William of Normandy defeated King Harold Godwinson at Hastings."),
            ("Who was the famous Carthaginian general who led war elephants across the Alps to invade Rome in 218 BC?",
             ["Hamilcar Barca", "Hannibal Barca", "Hasdrubal", "Scipio"], 1, 55,
             "Hannibal achieved stunning victories at Trebia, Lake Trasimene, and Cannae during the Second Punic War."),
            ("What peace treaty signed in 1648 concluded the devastating Thirty Years' War in Europe?",
             ["Peace of Westphalia", "Treaty of Utrecht", "Treaty of Tordesillas", "Peace of Augsburg"], 0, 60,
             "The Peace of Westphalia established the principle of state sovereignty in international law."),
            ("Which Roman Emperor legalized Christianity throughout the empire with the Edict of Milan in 313 AD?",
             ["Nero", "Marcus Aurelius", "Constantine the Great", "Diocletian"], 2, 50,
             "Constantine also founded Constantinople as the new capital of the Roman Empire."),
            ("Who was the female pharaoh of Egypt's 18th Dynasty who built the spectacular mortuary temple at Deir el-Bahari?",
             ["Cleopatra", "Nefertiti", "Hatshepsut", "Twosret"], 2, 55,
             "Hatshepsut reigned as pharaoh for over two decades, presiding over flourishing trade expeditions."),
            ("What naval battle in 1571 saw the Holy League defeat the main fleet of the Ottoman Empire?",
             ["Battle of Trafalgar", "Battle of Lepanto", "Battle of Actium", "Battle of Navarino"], 1, 60,
             "Lepanto was the last major naval engagement in the Mediterranean fought entirely between rowing galleys."),
            ("Who was the founder of the Mongol Empire who united the nomadic tribes in 1206?",
             ["Kublai Khan", "Genghis Khan (Temüjin)", "Batu Khan", "Ögedei Khan"], 1, 50,
             "Genghis Khan established the largest contiguous land empire in human history."),
            ("What English philosopher published 'Leviathan' in 1651, arguing for social contract theory?",
             ["John Locke", "Thomas Hobbes", "Jean-Jacques Rousseau", "David Hume"], 1, 55,
             "Hobbes argued that without strong political authority, human life would be 'solitary, poor, nasty, brutish, and short'."),
            ("In what year did the Western Roman Empire conventionally fall when Romulus Augustulus was deposed?",
             ["395 AD", "410 AD", "476 AD", "1453 AD"], 2, 55,
             "The Germanic chieftain Odoacer deposed the last Western Roman emperor in Ravenna in 476 AD."),
            ("Which dynasty ruled China for nearly three centuries from 1368 to 1644, building the Forbidden City?",
             ["Song Dynasty", "Ming Dynasty", "Tang Dynasty", "Qing Dynasty"], 1, 55,
             "The Ming Dynasty moved the capital to Beijing and oversaw the maritime voyages of Admiral Zheng He."),
            ("What 1814-1815 international conference remade the map of Europe after the downfall of Napoleon?",
             ["Congress of Vienna", "Treaty of Berlin", "Versailles Conference", "Potsdam Conference"], 0, 55,
             "Chaired by Austrian statesman Klemens von Metternich, the Congress restored balance of power in Europe."),
            ("Who was the Prussian leader known as the 'Iron Chancellor' who orchestrated German unification in 1871?",
             ["Wilhelm I", "Otto von Bismarck", "Helmut von Moltke", "Frederick the Great"], 1, 55,
             "Bismarck unified German states through diplomacy and three decisive wars (against Denmark, Austria, and France)."),
            ("What ancient city was destroyed and preserved by the catastrophic eruption of Mount Vesuvius in 79 AD?",
             ["Herculaneum and Pompeii", "Carthage", "Ephesus", "Alexandria"], 0, 50,
             "Pompeii was buried under meters of volcanic ash, preserving buildings, frescoes, and artifacts intact."),
            ("Which naval battle in 1805 off the coast of Spain saw Admiral Lord Nelson defeat the combined French and Spanish fleets?",
             ["Battle of the Nile", "Battle of Trafalgar", "Battle of Jutland", "Battle of Midway"], 1, 55,
             "Trafalgar confirmed British naval supremacy for over a century; Nelson was mortally wounded during the battle."),
            ("Who was the Persian King who founded the Achaemenid Empire and issued a famous cylinder of human rights in 539 BC?",
             ["Darius the Great", "Cyrus the Great", "Xerxes I", "Cambyses II"], 1, 55,
             "Cyrus the Great liberated the Jewish people from Babylonian captivity and established a vast, tolerant empire."),
            ("What 1494 treaty divided newly discovered non-European lands between the Portuguese and Spanish empires?",
             ["Treaty of Tordesillas", "Treaty of Utrecht", "Treaty of Madrid", "Treaty of Zaragoza"], 0, 60,
             "Signed at Tordesillas, Spain, it established a meridian 370 leagues west of the Cape Verde islands."),
            ("Which Italian polymath was sentenced to life imprisonment under house arrest by the Roman Inquisition in 1633?",
             ["Giordano Bruno", "Galileo Galilei", "René Descartes", "Johannes Kepler"], 1, 50,
             "Galileo was condemned for defending the Copernican theory that Earth moves around the Sun."),
            ("What code of laws codified under Emperor Justinian I in 529 AD formed the basis of Western civil law?",
             ["Corpus Juris Civilis", "Napoleonic Code", "Twelve Tables", "Edict of Nantes"], 0, 60,
             "The Corpus Juris Civilis synthesized centuries of Roman legal jurisprudence in Constantinople."),
            ("Who was the first woman to win a Nobel Prize, and the only person to win Nobel Prizes in two different sciences?",
             ["Rosalind Franklin", "Marie Curie", "Lise Meitner", "Dorothy Hodgkin"], 1, 50,
             "Marie Curie won the 1903 Nobel Prize in Physics and the 1911 Nobel Prize in Chemistry."),
            ("What conflict fought between 1337 and 1453 pitted the House of Plantagenet against the House of Valois?",
             ["War of the Roses", "Hundred Years' War", "Thirty Years' War", "Seven Years' War"], 1, 55,
             "The Hundred Years' War saw Joan of Arc rally French forces to liberate Orléans.")
        ]
    },
    "General Knowledge": {
        "Easy": [
            ("How many days are there in a standard leap year?",
             ["364 Days", "365 Days", "366 Days", "367 Days"], 2, 15,
             "A leap year occurs every four years, adding February 29 to keep the calendar synchronized with Earth's orbit."),
            ("Which navigation instrument uses Earth's magnetic field to determine north?",
             ["Barometer", "Compass", "Speedometer", "Altimeter"], 1, 15,
             "A magnetic compass needle aligns with Earth's geomagnetic field lines."),
            ("What is the official currency of Japan?",
             ["Won", "Yuan", "Yen", "Ringgit"], 2, 15,
             "The Japanese Yen (¥) is the third most traded currency in the global foreign exchange market."),
            ("How many primary colors exist in traditional pigment painting?",
             ["2 Colors", "3 Colors (Red, Blue, Yellow)", "4 Colors", "5 Colors"], 1, 15,
             "Red, Blue, and Yellow cannot be formed by mixing any other pigment colors."),
            ("What is the largest living mammal species on planet Earth?",
             ["African Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], 1, 15,
             "The Antarctic blue whale can grow up to 30 meters in length and weigh nearly 200 metric tons."),
            ("How many hours are there in one complete Earth day?",
             ["12 Hours", "24 Hours", "36 Hours", "48 Hours"], 1, 15,
             "One solar day consists of 24 hours (1,440 minutes)."),
            ("Which musical instrument has 88 keys and produces sound by hammers striking strings?",
             ["Accordion", "Piano", "Harpsichord", "Organ"], 1, 15,
             "A standard modern piano has 52 white natural keys and 36 black accidental keys."),
            ("How many players are on the field for one team in a standard soccer (football) match?",
             ["9 Players", "10 Players", "11 Players", "12 Players"], 2, 15,
             "Each team plays with 11 players including one designated goalkeeper."),
            ("What is the official currency of the United Kingdom?",
             ["Euro", "Pound Sterling", "Dollar", "Franc"], 1, 15,
             "The British Pound Sterling (£) is one of the world's oldest currencies still in continuous use."),
            ("How many minutes are in two full hours?",
             ["60 Minutes", "90 Minutes", "120 Minutes", "150 Minutes"], 2, 15,
             "Each hour contains 60 minutes, so 2 hours equal 120 minutes."),
            ("What is the opposite direction of North on a standard compass rose?",
             ["East", "West", "South", "North-East"], 2, 15,
             "South lies 180 degrees directly opposite of North."),
            ("What language is the most widely spoken native language in the world?",
             ["English", "Mandarin Chinese", "Spanish", "Hindi"], 1, 20,
             "Mandarin Chinese has over 900 million native speakers worldwide."),
            ("What color do you obtain by mixing red paint with yellow paint?",
             ["Green", "Orange", "Purple", "Brown"], 1, 15,
             "Mixing the two primary colors red and yellow produces the secondary color orange."),
            ("How many months of the calendar year have exactly 31 days?",
             ["5 Months", "6 Months", "7 Months", "8 Months"], 2, 15,
             "Seven months have 31 days: January, March, May, July, August, October, and December."),
            ("Which bird is globally recognized as a universal symbol of peace?",
             ["Eagle", "Dove", "Raven", "Falcon"], 1, 15,
             "The white dove carrying an olive branch is a universal symbol of peace and harmony."),
            ("What is the currency of the United States of America?",
             ["Euro", "US Dollar", "Pound", "Peso"], 1, 15,
             "The US Dollar ($) is the world's primary global reserve currency."),
            ("How many rings are interlocked in the official Olympic Games symbol?",
             ["4 Rings", "5 Rings", "6 Rings", "7 Rings"], 1, 15,
             "The 5 Olympic rings represent the five inhabited continents united in the Olympic movement."),
            ("What is the common term for a doctor who specializes in treating teeth and gums?",
             ["Optometrist", "Dentist", "Podiatrist", "Dermatologist"], 1, 15,
             "Dentists specialize in oral health diagnosis, prevention, and treatment."),
            ("How many centimeters are there in one meter?",
             ["10 cm", "100 cm", "1,000 cm", "10,000 cm"], 1, 15,
             "The metric prefix 'centi-' indicates one-hundredth: 1 meter = 100 centimeters."),
            ("What type of vehicle travels underneath the surface of the ocean?",
             ["Helicopter", "Submarine", "Hovercraft", "Barge"], 1, 15,
             "Submarines use ballast tanks to control buoyancy and navigate underwater.")
        ],
        "Medium": [
            ("Which international agency within the United Nations oversees global public health from Geneva?",
             ["UNESCO", "World Health Organization (WHO)", "UNICEF", "World Bank"], 1, 30,
             "The WHO was founded in 1948 in Geneva, Switzerland, to direct international public health policy."),
            ("What chess piece can move in an L-shaped path and jump over other pieces on the board?",
             ["Bishop", "Knight", "Rook", "Pawn"], 1, 30,
             "The knight moves two squares horizontally or vertically and then one square perpendicular."),
            ("What is the official currency shared by 20 member states of the European Union?",
             ["British Pound", "Euro (€)", "Swiss Franc", "Krona"], 1, 30,
             "The Euro was introduced in 1999 and is used daily by over 340 million European citizens."),
            ("What is the official language spoken in Brazil?",
             ["Spanish", "Portuguese", "French", "Italian"], 1, 30,
             "Brazil is the only Portuguese-speaking nation in the Americas due to colonization by Portugal in 1500."),
            ("What is the international telephone country calling code for Australia?",
             ["+1", "+44", "+61", "+81"], 2, 30,
             "Dialing +61 connects international telephone calls to Australia."),
            ("Which planet is the largest planet in our entire Solar System?",
             ["Saturn", "Jupiter", "Uranus", "Neptune"], 1, 30,
             "Jupiter's mass is more than double that of all other planets in the Solar System combined."),
            ("How many individual squares make up a standard international chessboard (8x8)?",
             ["48 Squares", "64 Squares", "72 Squares", "81 Squares"], 1, 30,
             "An 8x8 chessboard contains exactly 64 alternating light and dark squares."),
            ("What is the national currency of the Commonwealth of Australia?",
             ["Australian Dollar (AUD)", "New Zealand Dollar", "Pound", "Rupee"], 0, 30,
             "Australia was the pioneer of resilient polymer bank notes in 1988."),
            ("In classical mythology, who was the Roman god of the sea holding a trident?",
             ["Jupiter", "Neptune", "Mars", "Mercury"], 1, 30,
             "Neptune corresponds to Poseidon in Greek mythology as lord of horses and oceans."),
            ("What is the name of the standard international airport coding system with 3-letter codes (e.g., JFK, LHR)?",
             ["ICAO Codes", "IATA Codes", "ISO Codes", "FAA Codes"], 1, 35,
             "The International Air Transport Association (IATA) assigns three-letter codes to commercial airports."),
            ("Which natural gemstone is made purely of crystallized carbon?",
             ["Ruby", "Diamond", "Emerald", "Sapphire"], 1, 30,
             "Diamonds are formed deep under high temperature and pressure in Earth's mantle."),
            ("What is the capital city of Canada?",
             ["Toronto", "Montreal", "Ottawa", "Calgary"], 2, 30,
             "Ottawa is the federal capital of Canada, situated in the province of Ontario."),
            ("What is the primary ingredient used to make traditional Japanese tofu?",
             ["Rice", "Soybeans", "Wheat", "Barley"], 1, 30,
             "Tofu is made by coagulating soy milk and pressing the resulting curds into soft blocks."),
            ("Which device is used to measure ambient air pressure in weather forecasting?",
             ["Anemometer", "Barometer", "Seismograph", "Hydrometer"], 1, 35,
             "A barometer measures atmospheric pressure, where dropping pressure often signals incoming storms."),
            ("What is the longest bone in the human body, located in the upper leg?",
             ["Tibia", "Femur", "Humerus", "Fibula"], 1, 30,
             "The femur (thigh bone) is both the longest and strongest bone in the human skeleton."),
            ("What is the collective noun commonly used to describe a group of lions?",
             ["Pack", "Pride", "Flock", "Herd"], 1, 30,
             "A social family group of lions is known as a pride."),
            ("Which international sports competition is held once every four years for athletes with disabilities?",
             ["Olympics", "Paralympic Games", "Commonwealth Games", "World Games"], 1, 30,
             "The Paralympic Games emphasize athletic excellence across physical, visual, and intellectual impairments."),
            ("In architecture, what is the central wedge-shaped stone at the apex of a masonry arch called?",
             ["Cornerstone", "Keystone", "Capston", "Lintel"], 1, 35,
             "The keystone locks all the arch's stones into position and bears structural compression."),
            ("What is the chemical name for common household table salt?",
             ["Sodium Bicarbonate", "Sodium Chloride", "Potassium Chloride", "Calcium Carbonate"], 1, 30,
             "Table salt consists of the ionic compound sodium chloride (formula NaCl)."),
            ("What is the term for a word that reads the exact same forwards and backwards (e.g., 'radar', 'level')?",
             ["Anagram", "Palindrome", "Acronym", "Homophone"], 1, 35,
             "A palindrome reads identically in either direction, such as 'madam' or 'racecar'.")
        ],
        "Hard": [
            ("In which Scandinavian city is the Nobel Peace Prize officially presented each December?",
             ["Stockholm, Sweden", "Oslo, Norway", "Copenhagen, Denmark", "Helsinki, Finland"], 1, 50,
             "Under Alfred Nobel's will, the Peace Prize is awarded in Oslo, while the scientific prizes are presented in Stockholm."),
            ("What is the collective noun for a flock of flamingos gathered together?",
             ["Gaggle", "Flamboyance", "Colony", "Murder"], 1, 55,
             "A group of flamingos is famously called a flamboyance because of their striking pink coloration."),
            ("What is recognized as the world's oldest continuously operating university, founded in 859 AD in Fez, Morocco?",
             ["University of Oxford", "University of Bologna", "University of al-Qarawiyyin", "Sorbonne University"], 2, 55,
             "Founded by Fatima al-Fihri, the University of al-Qarawiyyin is recognized by UNESCO as the oldest operational university."),
            ("Who painted the world-famous post-impressionist masterpiece 'The Starry Night' in June 1889?",
             ["Claude Monet", "Vincent van Gogh", "Paul Cézanne", "Henri Matisse"], 1, 50,
             "Van Gogh painted 'The Starry Night' depicting the pre-dawn view from his asylum room window at Saint-Rémy."),
            ("What is the highest-grossing original animated film category studio founded by Hayao Miyazaki and Isao Takahata?",
             ["Pixar", "Studio Ghibli", "DreamWorks", "Aardman"], 1, 50,
             "Studio Ghibli produced beloved global animated masterworks including 'Spirited Away' and 'My Neighbor Totoro'."),
            ("What is the international metric SI unit of magnetic flux density?",
             ["Tesla", "Gauss", "Weber", "Henry"], 0, 55,
             "One tesla is equal to one weber per square meter, named in honor of Nikola Tesla."),
            ("What is the name of the ancient library in Egypt considered one of the largest in antiquity?",
             ["Library of Pergamum", "Library of Alexandria", "Library of Celsus", "Villa of the Papyri"], 1, 50,
             "The Great Library of Alexandria was a world center of scholarship from the 3rd century BC until its destruction."),
            ("What is the scientific term for the study of tree rings to date environmental events?",
             ["Palynology", "Dendrochronology", "Speleology", "Stratigraphy"], 1, 60,
             "Dendrochronology analyzes annual growth ring patterns in trees to date past climate conditions."),
            ("What is the standard nautical unit of speed equal to one nautical mile per hour (1.852 km/h)?",
             ["Knot", "Fathom", "Cable", "League"], 0, 50,
             "One knot equals exactly 1.852 kilometers per hour used globally in aviation and maritime navigation."),
            ("What was the name of the first artificial satellite launched into orbit by humanity in October 1957?",
             ["Explorer 1", "Sputnik 1", "Vanguard 1", "Telstar"], 1, 50,
             "Sputnik 1 was launched by the Soviet Union on October 4, 1957, beginning the Space Age."),
            ("What rare, naturally occurring atmospheric optical phenomenon produces iridescent rings around the Sun or Moon?",
             ["Aurora", "Corona / Halo", "Mirage", "Crepuscular rays"], 1, 55,
             "Halos are produced by hexagonal ice crystals suspended in high-altitude cirrus clouds."),
            ("What is the name of the musical tempo marking that indicates playing very fast and lively?",
             ["Adagio", "Andante", "Presto", "Largo"], 2, 55,
             "In classical musical terminology, presto indicates a very fast, lively tempo."),
            ("What rare gas was first discovered in the solar spectrum before being identified on Earth in 1895?",
             ["Neon", "Argon", "Helium", "Krypton"], 2, 55,
             "Helium was detected as an unknown yellow spectral line in sunlight during an 1868 solar eclipse."),
            ("Which international committee awards the annual Pritzker Prize, often dubbed the Nobel Prize of architecture?",
             ["Hyatt Foundation", "Royal Institute", "UNESCO", "Aga Khan Trust"], 0, 60,
             "Founded by Jay A. Pritzker in 1979, the prize honors living architects for significant contributions."),
            ("What is the standard cryptographic hash algorithm producing a 256-bit signature widely used in cybersecurity?",
             ["MD5", "SHA-256", "DES", "Blowfish"], 1, 55,
             "SHA-256 belongs to the SHA-2 family designed by the National Security Agency and is central to blockchain security."),
            ("What geological epoch encompasses the time from the end of the last ice age (11,700 years ago) to the present?",
             ["Pleistocene", "Holocene", "Pliocene", "Miocene"], 1, 55,
             "The Holocene epoch witnessed the development and spread of human civilizations and agriculture."),
            ("Which ancient philosopher was sentenced to death in Athens in 399 BC for 'corrupting the youth'?",
             ["Plato", "Aristotle", "Socrates", "Epicurus"], 2, 50,
             "Socrates chose to drink poison hemlock rather than compromise his philosophical inquiry."),
            ("What is the chemical name of the neurotransmitter whose deficiency is linked to clinical depression and sleep regulation?",
             ["Dopamine", "Serotonin", "Acetylcholine", "GABA"], 1, 55,
             "Serotonin (5-hydroxytryptamine) regulates mood, appetite, cognitive function, and circadian rhythm."),
            ("What international treaty adopted in 1987 phased out chlorofluorocarbons (CFCs) to protect the ozone layer?",
             ["Kyoto Protocol", "Montreal Protocol", "Paris Agreement", "Basel Convention"], 1, 55,
             "The Montreal Protocol is universally recognized as the most successful international environmental agreement in history."),
            ("What is the world's most consumed beverage after plain drinking water?",
             ["Coffee", "Tea", "Milk", "Orange Juice"], 1, 50,
             "Tea made from Camellia sinensis is consumed by billions across all continents every day.")
        ]
    }
}

# Compile into TypeScript format
quiz_items = []
quiz_counter = 1

for category, difficulties in categories_data.items():
    for diff, questions in difficulties.items():
        # Map difficulty to type
        diff_type = "Beginner" if diff == "Easy" else ("Intermediate" if diff == "Medium" else "Advanced")
        for q_text, options, correct_idx, points, fact in questions:
            q_id = f"quiz_{category[:3].lower()}_{diff[:3].lower()}_{quiz_counter}"
            quiz_counter += 1
            
            # Escape strings safely
            safe_q = q_text.replace('"', '\\"').replace("'", "\\'")
            safe_fact = fact.replace('"', '\\"').replace("'", "\\'")
            
            # Format options cleanly
            opt_strs = []
            for i, opt in enumerate(options):
                clean_opt = opt.replace('"', '\\"').replace("'", "\\'")
                opt_strs.append(f"'{clean_opt}'")
            
            item = {
                "id": q_id,
                "category": category,
                "difficulty": diff_type,
                "question": safe_q,
                "options": opt_strs,
                "correctIndex": correct_idx,
                "points": points,
                "fact": safe_fact
            }
            quiz_items.append(item)

# Build TypeScript file content
ts_code = """import { QuizItem } from '../types';

/**
 * Universal Global Quiz Curriculum for JoyEarn
 * 5 Categories x 3 Difficulty Tiers x 20 Questions each = 300 Questions.
 * 100% Policy-compliant, zero regional/country-specific bias.
 * All questions feature 4 distinct options (A, B, C, D) and educational explanations.
 */
export const ALL_QUIZZES: QuizItem[] = [
"""

for item in quiz_items:
    ts_code += "  {\n"
    ts_code += f"    id: '{item['id']}',\n"
    ts_code += f"    category: '{item['category']}',\n"
    ts_code += f"    difficulty: '{item['difficulty']}',\n"
    ts_code += f"    question: '{item['question']}',\n"
    ts_code += f"    options: [{', '.join(item['options'])}],\n"
    ts_code += f"    correctIndex: {item['correctIndex']},\n"
    ts_code += f"    points: {item['points']},\n"
    ts_code += f"    fact: '{item['fact']}',\n"
    ts_code += "  },\n"

ts_code += "];\n"

out_path = os.path.join(os.path.dirname(__file__), "src", "data", "quizDatabase.ts")
with open(out_path, "w", encoding="utf-8") as f:
    f.write(ts_code)

print(f"Successfully generated {len(quiz_items)} universal questions at {out_path}!")
for cat in categories_data:
    for d in ["Easy", "Medium", "Hard"]:
        count = len(categories_data[cat][d])
        print(f"  [{cat}] - {d}: {count} questions")
